### ISSUE TITLE
Allow to revert stored default app to original default

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#1033]
About the feature of the trash button to 'reset' to default project settings, You'll create a new issue for that?

_Originally posted by @tacsio in https://github.com/quarkusio/code.quarkus.io/issues/1029#issuecomment-1259491658_

**Comment by ia3andy** [comment]
@tacsio could you add a comment so I can assign it to you? I will wait for this one to make the twitter announcement as I think it will make this feature really complete wdyt?

**Comment by tacsio** [comment]
Hey @ia3andy,

what do You think about these options?

#### Trash icon in button only when project config exists in localstorage:
![option1](https://user-images.githubusercontent.com/353197/192860021-58f6ac61-0140-47a9-beb6-7b4c1ae37593.gif)

#### New button to reset to default
![option2](https://user-images.githubusercontent.com/353197/192860299-e32215a1-552b-4028-9113-0ac467b95494.gif)

**Comment by ia3andy** [comment]
I think I prefer the first option it's more concise. Could you create PR with option 1? I'll have the preview in it.

**Comment by tacsio** [comment]
Ok.

I haven't finished the tests yet. 
I was waiting for the chosen option to write some tests.

**Comment by ia3andy** [comment]
@tacsio fyi your first PR is live :)

**Comment by tacsio** [comment]
> I think I prefer the first option it's more concise. Could you create PR with option 1? I'll have the preview in it.

@ia3andy, PR created!
