### ISSUE TITLE
Show status (CR1, ALPHA1, ...) when stream is selected in dropdown

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#1069]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2223984/199504237-0de37e61-f76b-40dd-95a7-d72b64c51512.png)

![image](https://user-images.githubusercontent.com/2223984/199504215-a87cfd14-cfc5-4a2e-a35c-70248357d53c.png)

Showing "recommended" is not necessary

**Comment by ia3andy** [comment]
@tacsio any interest in that one?

**Comment by tacsio** [comment]
Sure! Could you assign that issue to me?

**Comment by tacsio** [comment]
@ia3andy, any changes needed?

#### Show Stream Status
![cr1](https://user-images.githubusercontent.com/353197/200069788-c20d5a3a-5af8-4523-9263-1bdabf963385.png)
#### Stream Status Empty
![empty](https://user-images.githubusercontent.com/353197/200069873-eaa5b7e3-f313-4538-82af-b4a4d251fc68.png)
#### Stream Status Dropdown
![print1](https://user-images.githubusercontent.com/353197/200069922-9c7f6ebf-0180-4c03-8f72-210336911188.png)
#### Recommended Stream
![recommended](https://user-images.githubusercontent.com/353197/200069944-6992f696-06a0-40f1-b567-060a991b700d.png)

**Comment by tacsio** [comment]
I have a question. 
Is there a problem with the StreamItem component always setting recommended prop as false?

https://github.com/quarkusio/code.quarkus.io/blob/698e1bde6afef6d1b084b41f642a2d5ee7208a97/library/components/header/stream-picker.tsx#L63

**Comment by ia3andy** [comment]
> I have a question. Is there a problem with the StreamItem component always setting recommended prop as false?
> 
> https://github.com/quarkusio/code.quarkus.io/blob/698e1bde6afef6d1b084b41f642a2d5ee7208a97/library/components/header/stream-picker.tsx#L63

I should just be a default value for this prop. When picked, we don't show recommended, so it's always false. Do you have an idea to make it cleaner?

**Comment by tacsio** [comment]
> 

Maybe if we create 2 components. One for dropdown item and another for display selected info.

**Comment by ia3andy** [comment]
> > 
> 
> Maybe if we create 2 components. One for dropdown item and another for display selected info.

go for it :)
