### ISSUE TITLE
Internal server error when generating project with the Kotlin extension 

### ISSUE THREAD

**Issue by xorye** [quarkusio/code.quarkus.io#110]
On https://code.quarkus.io/, generating any project with the Kotlin extension results in an internal server error.

![image](https://user-images.githubusercontent.com/20326645/63804942-4a887180-c8e6-11e9-9d41-2e234c5b2e85.png)

**Comment by ia3andy** [comment]
Good catch @xorye thanks!!

It's missing resources in the Quarkus binary. I'll provide a fix this morning.

@gastaldi @gsmet any new about supporting Sentry (or such) in Quarkus?

**Comment by ia3andy** [comment]
Shit, this is a bug in Quarkus core:
```
mvn io.quarkus:quarkus-maven-plugin:0.21.1:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=rest-kotlin \
    -DclassName="org.acme.rest.GreetingResource" \
    -Dpath="/greeting" \
    -Dextensions="kotlin,resteasy-jsonb"

...
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.21.1:create (default-cli) on project standalone-pom: Template resource is missing: /templates/basic-rest/kotlin/pom.xml-template.ftl -> [Help 1]

```

This is not working anymore.. I am creating an issue in Quarkus.

**Comment by ia3andy** [comment]
Waiting for Quarkus Release..
