### ISSUE TITLE
Add a "Missing a feature?" rubbon pointing to GitHub issue for code.quarkus.io

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/code.quarkus.io#113]
It would show that we are both in beta and listening to feedback.

**Comment by ia3andy** [comment]
![image](https://user-images.githubusercontent.com/2223984/64963172-1f67c100-d899-11e9-8f0a-f96cca60f9d4.png)

@emmanuelbernard I didn't spend too much time on it, is that ok?

**Comment by emmanuelbernard** [comment]
I was thinking of it being prominent, with an actual ribbon  fork me on GitHub style

**Comment by jkbrock** [comment]
We have some patterns established to post announcements in banners of
different colors.

This kind of thing might warrant its own announcement.

Jason Brock

Web UX Designer, Middleware Engineering Services

Red Hat Austin, Texas <https://www.redhat.com/>

He, Him, & His | jbrock@redhat.com | 512-786-8304
<https://www.redhat.com/>

**Comment by edewit** [comment]
`s/feedback/feedbacks/g` feedback is uncountable (literally :stuck_out_tongue:)

@jkbrock do you have some example of these "established patterns"
