### ISSUE TITLE
Be able to have &extension-search= be the equivalent of an empty filter search

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/code.quarkus.io#1136]
It's currently not possible to bring up a page that shows both platform and non-platform extensions. The default page shows platform, and if it's overridden, then only non-platform show. It would be nice (but not desperately essential) to be able to show both. 

See discussion at https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Viewing.20*all*.20extensions.20on.20code.2Equarkus.2Eio/near/325365910

**Comment by ia3andy** [comment]
This is done
