### ISSUE TITLE
Send the Quarkus version in the Google Analytics events

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/code.quarkus.io#114]

**Comment by ia3andy** [comment]
@emmanuelbernard do you mean in all the events?

**Comment by emmanuelbernard** [comment]
Good question but I'm tempted to say yes. Thoughts?
We can start with one per project creation for now though as we are not supporting multiple version for now

**Comment by ia3andy** [comment]
@emmanuelbernard I think it would make total sense to add the version in the `App.Generate` event. 

For the others events, I am not sure..

**Comment by emmanuelbernard** [comment]
ok let's start with that
