### ISSUE TITLE
Add a "Push to GitHub" button in the "Zip Next Step" modal 

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/code.quarkus.io#1176]
see subject

**Comment by ia3andy** [comment]
Yeah that's a very good point!

**Comment by haseeb-xd** [comment]
I want to contribute. Can you please add a screenshot for clarity? As I am new I don't know where I've to put the button.

**Comment by ia3andy** [comment]
@haseeb-xd 
<img width="661" alt="Capture d’écran 2023-04-06 à 10 38 57" src="https://user-images.githubusercontent.com/2223984/230323565-1141ce27-2ec7-4521-b90e-5e7cf267491c.png">

**Comment by shivam-sharma7** [comment]
@maxandersen close this, already done
