### ISSUE TITLE
Add version 3.x

### ISSUE THREAD

**Issue by karstengresch** [quarkusio/code.quarkus.io#1194]
**Description**
The version selector in the header right to the Quarkus logo allows selecting 2.13 and 2.70. I't be great if a 3.x version could also be selected (as seen on https://code.quarkus.io/).

**Comment by maxandersen** [comment]
It shows for me. Got a screenshot?

**Comment by karstengresch** [comment]
Doh. Coming from https://code.quarkus.redhat.com/ -> linked in an official preso :-|

https://code.quarkus.redhat.com/ also links to this repo for submitting an issue. :-O

**Comment by karstengresch** [comment]
Closing, seems to be a RH internal problem that cannot be addressed here.

**Comment by maxandersen** [comment]
Once red hat build of quarkus has a 3.x version it will show up.
