### ISSUE TITLE
null status breaks intellij-quarkus's Wizard

### ISSUE THREAD

**Issue by fbricon** [quarkusio/code.quarkus.io#1241]
This change from #1240 
https://github.com/quarkusio/code.quarkus.io/blob/fcf86861ee7f63c19659c76b80fcbbfef2f1f792/api/src/main/kotlin/io/quarkus/code/model/Stream.kt#L8

causes intellij-quarkus to [break on `null` status ](https://github.com/redhat-developer/intellij-quarkus/issues/1124)
<img width="560" alt="Screenshot 2023-08-23 at 23 05 24" src="https://github.com/quarkusio/code.quarkus.io/assets/148698/61f7e136-edbf-481b-b63a-5c279e5f8bda">

**Comment by fbricon** [comment]
Even if  intellij-quarkus releases a fix first, users stuck on older versions will still be broken, so I strongly recommend code.quarkus.io to restore its old behavior

cc @maxandersen

**Comment by ia3andy** [comment]
@fbricon my bad, I'll fix the api today!

**Comment by fbricon** [comment]
@ia3andy thanks, I confirm it works against https://stage.code.quarkus.io. When will it be pushed to prod?

**Comment by ia3andy** [comment]
> @ia3andy thanks, I confirm it works against https://stage.code.quarkus.io. When will it be pushed to prod?

It is in prod

**Comment by fbricon** [comment]
yes indeed, thanks
