### ISSUE TITLE
Add Java 21 to the "Java version" dropdown

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/code.quarkus.io#1251]
**Description**
The "Java version" dropdown only offers 11 and 17:

![image](https://github.com/quarkusio/code.quarkus.io/assets/412878/0dc5e4cf-210a-44d1-a579-b497a985b29a)

But Java 21 is now officially supported: https://quarkus.io/blog/quarkus-3-5-0-released/

So we should add Java 21 to the dropdown.

**Comment by ia3andy** [comment]
We don't have the ubi8 jdk 21: https://access.redhat.com/discussions/7039772, Until this is available we can't generate project with Java 21 (AFAIK). You may always switch the Java version in your pom.xml until then.

**Comment by rokkolesa** [comment]
It seems the image is now available: registry.access.redhat.com/ubi8/openjdk-21:1.18 (as well as the ubi9 counterpart: registry.access.redhat.com/ubi9/openjdk-21:1.17).

**Comment by ia3andy** [comment]
This is now in production :)
