### ISSUE TITLE
JDK 21 with Intellij

### ISSUE THREAD

**Issue by mjmk3** [quarkusio/code.quarkus.io#1266]
In Intellij I can't create project with jdk 21 still only take 17 and 11, I have to generate code from website. Hope to fix this bug as soon as possible

**Comment by ia3andy** [comment]
Here is where you should create this issue: https://github.com/redhat-developer/intellij-quarkus

cc @angelozerr

**Comment by ia3andy** [comment]
The Code Quarkus api gives all the information: https://code.quarkus.io/api/streams
