### ISSUE TITLE
hovering copy to clipboard incorrectly also enables hover on checkbox

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/code.quarkus.io#128]
Hovering(or clicking) on copy to clipboard icon also enables the hover on the checkbox.
Took me a while to realize it was a different thing than just select :)

![2019-09-06_11-15-04](https://user-images.githubusercontent.com/54129/64416563-ac3f9d00-d097-11e9-99dd-ab715d7b9985.png)

note: once clicked the hover disappear again and the selection doesn't stay - so its just a visual glitch.

**Comment by ia3andy** [comment]
Good catch
