### ISSUE TITLE
Find a way to have missing core extensions displayed

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#129]
We need to have missing "Core Extensions" pre-selected  and readonly visible in the UI.
![image](https://user-images.githubusercontent.com/2223984/64430690-19175f00-d0b9-11e9-88fc-9913e07ba3b4.png)

CC @emmanuelbernard

**Comment by emmanuelbernard** [comment]
Not visible I think as they are going to be included for the user and are too much details.
