### ISSUE TITLE
Checkboxes sometimes stay selected after hovering

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#134]
Reported by @tqvarnst, if you move the mouse up and down over the check-boxes it seems to miss some events and the check-box remains checked. See picture:
![image](https://user-images.githubusercontent.com/2223984/64431702-3c430e00-d0bb-11e9-9134-40086da094c2.png)

@tqvarnst could you specify browser please?

**Comment by tqvarnst** [comment]
Google Chrome Version 76.0.3809.132 (Official Build) (64-bit) on Mac OS
Mojave 10.14.6 (build 18G95) MacBook Pro (15-inch, 2017) 3.1 GHz Intel Core
i7, 16 GB.

----
Thomas Qvarnström
Sr. Pr. Product Manager
Red Hat, Inc.


Den fre 6 sep. 2019 kl 15:31 skrev Andy Damevin <notifications@github.com>:

**Comment by ia3andy** [comment]
Thanks @tqvarnst, could you test that it is fixed please :)
