### ISSUE TITLE
Adjust extension sorting and filters to put selected extensions at the top

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/code.quarkus.io#1365]
If I visit a URL like this https://code.quarkus.io/?e=io.quarkiverse.langchain4j%3Aquarkus-langchain4j-core, it looks like the query parameters didn't work:

<img width="1570" alt="image" src="https://github.com/quarkusio/code.quarkus.io/assets/11509290/c509e535-7996-49c0-88bf-f01bbf968199">

I can tell that some extensions were selected if I know to look at the number next to the rocket, but that needs a good understanding. Even if I scroll lots, I don't see my extensions, because of the `origin:platform` filter.

If I want to deselect the extensions, I need to know to remove the filter, and then do a *lot* of scrolling. 

Would it make sense to put extensions which are selected at the top of the list? It might be annoying to have them jump around on clicking, but in the query parameter case, I think it would only help.

**Comment by ia3andy** [comment]
@holly-cummins when you arrive the cart is supposed to be visible on the page and you can delete it from the cart

**Comment by holly-cummins** [comment]
@ia3andy I'm not sure it's working as intended. If I reload the page I do see a floating section showing the selected extension, but I couldn't even screenshot it to confirm it was the cart you meant, because it disappears so quickly. I don't think I'd be able to use it to delete extensions, because it goes away too fast (<5s?). 

I can also see my selected extensions if I know to hover over the rocket symbol, but that kind of needs people to know the mechanism is there.

**Comment by ia3andy** [comment]
Ok so maybe I should keep it open and the user has to close it?

**Comment by holly-cummins** [comment]
I think the current behaviour is good when someone clicks on an extension, interactively - it gives them some feedback that their click worked, and reminds them what else they have selected, and then goes away. I think in that situation if the cart stayed, it would be annoying. 

And, when people are interacting with the page, the extension they selected *has* to be on the screen, or they couldn't have selected it.

The problem is mostly when selecting happens via a URL query string (for example,  https://code.quarkus.io/?e=io.quarkiverse.langchain4j%3Aquarkus-langchain4j-core).  The extension people selected is probably not visible on the page, and sometimes, because of the default `filter:platform` filter, they wouldn't even be able to find it by scrolling. So a persistent cart would help ... but I think what would be better is to get something closer to the "I just scrolled to find an extension" behaviour, and have the actual listing of the extension be visible. That way they can see the full extension description,  and maybe select the extensions that are next to it in the list. The way we get it visible could be by adjusting the sorting of the list, or if dynamic ordering is too confusing, it could just be by "pre-scrolling" the list to the right point. 

I tried to do a screenshot of what I meant for  https://code.quarkus.io/?e=io.quarkiverse.langchain4j%3Aquarkus-langchain4j-core, but I actually can't find the right point in the list to screenshot by manual scrolling (even after clearing the platform filter). 

The right behaviour if multiple extensions are pre-selected is harder to figure out, but that scenario is less likely (for now).

**Comment by ia3andy** [comment]
It's pretty much the same when you go on any shopping website, so I am in favor of making this a bit nicer by making it more obvious when you arrive on the page (using a popup or whatever). I am not in favor of changing the list order, that would be too weird I think.

**Comment by holly-cummins** [comment]
But if I go to, say, [https://www.amazon.co.uk/Enterprise-OSGi-Action-Holly-Cummins/dp/1617290130, I can see _Enterprise O](https://www.amazon.co.uk/s?k=quarkus&crid=2936QVWZ9Q8M4&sprefix=quarkus%2Caps%2C119&ref=nb_sb_noss_1), I see a bunch of books about Quarkus. I don't see a homepage showing random other items. Same if I visit https://www.amazon.co.uk/Full-Stack-Quarkus-React-Hands/dp/180056273X/ref=sr_1_1?crid=2936QVWZ9Q8M4&dib=eyJ2IjoiMSJ9.o3O2NnS8QN3BQ_G2pd3gtP0espaGawZco5zuMDdStmJVxPHPC5AwUtkXus1hmOiiVOLvgPZ_JtTCuAsAbnniu1O1UDU6fBvoSmep3yWDxu6qXIYF9JUCfCIIcTj1_WUy1znzkJbPOl4JoULruMkcx3FVPBc9NffKdYBrMtWHQ4XV2Qpi2jSqb0YQ4AGp_Iw7Y-Umv_XekaCKxtt4dAv8owdQZKiOCWBQmOUUMnxyQ_A.XTAM1iuORE0M4KI-2feusuzLS-AUIpt_8jgymbgGPmk&dib_tag=se&keywords=quarkus&qid=1719393156&sprefix=quarkus%2Caps%2C119&sr=8-1

Those examples a little bit different since in the code.quarkus case the query is a "select this item" query, not a search query. I can't figure out what the equivalent would be for a shopping website.... but I'd be surprised if a shopping website ever allowed me to have a link which put an item in my basket while taking me to a homepage which didn't even show the thing I was interested in. 

If you don't want to re-order, what about position the scroll bar so the user is at the right point in the list? That feels very natural, and much more consistent with what users would expect than the current behaviour.

**Comment by ia3andy** [comment]
We now have the selected extension displayed on the main screen
