### ISSUE TITLE
Make code-quarkus.io "curl" aware

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/code.quarkus.io#151]
**Description**

It will be great that we can generate a project also from `curl`. In fact, it should be not so hard as the HTML button at the end calls a URL with some parameters. Maybe it needs to be refactored/offered a new REST endpoint.

But for example, doing `curl https://code.quarkus.io/` should return a zip with the defaults (as if I pushed the button just after landing on the page). Then you could do something like `curl https://code.quarkus.io?group=org.acme&artifact=quick&extensions=x, y, z`

This would be really nice because then the creation of a Quarkus project would be sharable, I just can send an URL endpoint to anyone (even with bit.ly) and it will create the project without having to install Maven or Gradle or having to navigate to a webpage. And this might be really interesting for Docker containers, as we can put this URL in a `Dockerfile` and the project will be installed automatically without having to relay un any other installed tool. Notice that `mvnw` is responsible at runtime to install Maven without having to have installed in the base image.

**Comment by ia3andy** [comment]
You can share urls :)
https://code.quarkus.io/api/download?g=org.acme&a=share-to-alex&v=1.0.0-SNAPSHOT&c=org.acme.ExampleResource&e=io.quarkus%3Aquarkus-resteasy&e=io.quarkus%3Aquarkus-resteasy-jackson

Only problem they are a bit long.. leading to #154.

**Comment by ia3andy** [comment]
![image](https://user-images.githubusercontent.com/2223984/65058812-2a901f00-d975-11e9-804f-0340607aa9c8.png)

**Comment by lordofthejars** [comment]
Yeah, also maybe this issue should be changed to doc issue so in this doc explains all the possible query parameters that you can use. But thanks, it is nice to see that it is already curl aware.

**Comment by ia3andy** [comment]
You have the doc there:
http://editor.swagger.io/?url=https://code.quarkus.io/openapi

There is a reference to it in the README, I could make that a bit clearer in the doc as you suggested:
https://github.com/quarkusio/code.quarkus.io#api-documentation

**Comment by lordofthejars** [comment]
Thanks :)

**Comment by ia3andy** [comment]
Closing :)
