### ISSUE TITLE
'org.kie.kogito:kogito-quarkus' is missing from the current stream '', it has been unselected.

### ISSUE THREAD

**Issue by koumgang** [quarkusio/code.quarkus.io#1514]
**Description**
(Describe the feature here.)
Hi, getting this error when trying to create a kogito project
'org.kie.kogito:kogito-quarkus' is missing from the current stream '', it has been unselected.
![Image](https://github.com/user-attachments/assets/dfbe0288-23cb-4aa8-8cd3-5318392f6c06)

**Comment by ia3andy** [comment]
@aloubyansky I don't see kogito listed anymore on code.quarkus.io is that normal?

**Comment by ia3andy** [comment]
OK this is a duplicate and has been explained here: https://github.com/quarkusio/code.quarkus.io/issues/1289
