### ISSUE TITLE
New rest-service preset

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#1528]
This would just select Quarkus Rest.

@insectengine we would need a new icon for this.

cc @maxandersen @tqvarnst @gsmet

**Comment by insectengine** [comment]
Version 1 using the rest symbol from music.

![Image](https://github.com/user-attachments/assets/cac63568-51c1-4e70-b80b-7ca9111c6b89)
![Image](https://github.com/user-attachments/assets/12227c39-8038-49bd-bfeb-932bc33845d5)

**Comment by ia3andy** [comment]
I really like the Zz :)

**Comment by hsmiranda** [comment]
Nice idea!
