### ISSUE TITLE
Download urls are too long, a tiny url feature would be great

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#154]

**Comment by edewit** [comment]
So how would you like to do this? One option would be to make the parameters shorter by removing all the parameter names using a fixed order then using only the values convert them to something like `value1|value2|value3`.

Or we create an unique number based on the parameters serverside and keep a mapping between the unique number (represented by something like '73WakrfVbNJBaAmhQtEeDv') and parameters send by the client. But then we need to think about how long do we keep this number and how (datbase or in memory).

Or do you want to use and external service to do this.

**Comment by ia3andy** [comment]
I was think about using an external service directly from the client, wdyt?

**Comment by jeffmaury** [comment]
I faced the problem when trying to generate a Quarkus app with all extensions select: the URL is 4981 char long thus the server respond with:
```

> Host: code.quarkus.io             
> User-Agent: curl/7.63.0           
> Accept: */*                       
>                                   
{ [5 bytes data]                    
* HTTP 1.0, assume close after body 
< HTTP/1.0 414 Request-URI Too Long 
```

**Comment by ia3andy** [comment]
We introduced a new shortId field to avoid this problem..
