### ISSUE TITLE
Black/empty screen when accessing with Internet Explorer 11

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/code.quarkus.io#158]
While looking at https://github.com/quarkusio/quarkusio.github.io/issues/111 I noticed that when you go to `https://code.quarkus.io` you get a complete black page. Making it completely broken.

Usage of IE 11 is low so I would not worry too much about supporting it fully, but I would suggest we at least detect the situation and popup message/page telling the user to Install a more modern browser.

**Comment by edewit** [comment]
Adding a polyfill makes it work, but then there are still style issues:
![image](https://user-images.githubusercontent.com/51133/67190785-e6b78c00-f3f0-11e9-9037-13a80306c32a.png)
```
import 'react-app-polyfill/ie11';
import 'core-js/es/number';
```
