### ISSUE TITLE
Options reset after application download

### ISSUE THREAD

**Issue by ambakshi** [quarkusio/code.quarkus.io#159]
Hello,
 It would be great if the application didn't reset your options after you have downloaded the zip file. I wanted to try downloading a few variations and see in how they differ. Great project, thanks for the hard work.

Thanks!
Amit

**Comment by ia3andy** [comment]
![image](https://user-images.githubusercontent.com/2223984/66756685-d6585c00-ee9a-11e9-85ed-c1b683f58e0c.png)

It's actually already the case if you click on "Go back" :)

We previously had a discussion about wether the label "Go back" was clear enough, maybe that means it's not. Didn't you see this button?
