### ISSUE TITLE
Quarkus extensions for Camel is not listed

### ISSUE THREAD

**Issue by ravishankarhassain** [quarkusio/code.quarkus.io#165]
Quarkus extensions for Apache Camel components is missing in https://code.quarkus.io/ website

In the camel github repo (https://github.com/apache/camel-quarkus/tree/master/extensions), as well in the camel website (https://camel.apache.org/camel-quarkus/latest/list-of-camel-quarkus-extensions.html), I can see few Apache Camel extension for Quarkus but its not listed in the webpage

**Comment by ia3andy** [comment]
This is waiting for another issue on Quarkus: https://github.com/quarkusio/quarkus/issues/3962
