### ISSUE TITLE
Introduce status flag for extension

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#196]
**Description**
For now only "Preview" will be visible, "Stable" extensions will be implicit.

**Comment by ia3andy** [comment]
It will need a tooltip explaining what "Preview" means, @emmanuelbernard could you write it?

**Comment by emmanuelbernard** [comment]
"This is work in progress. API or configuration properties might change as the extension matures. Give us your feedback :)

**Comment by maxandersen** [comment]
metadata now have "status" = "preview"  in them; I saw *some* have "status" = "stable" too but not all but no status should be treated as if status = stable or rather status != preview at this stage.
