### ISSUE TITLE
Cannot find any http extensions in the code.quarkus.io

### ISSUE THREAD

**Issue by davsclaus** [quarkusio/code.quarkus.io#201]
If you type http in the search extensions then you do not find any. There should be a vert.x http client extension or something for http client usages

https://code.quarkus.io/

**Comment by ia3andy** [comment]
@emmanuelbernard any thought?

**Comment by emmanuelbernard** [comment]
yes I'm adding some keywords as we speak. vert.x http no because that's an internal one. But vert.x web, undertow and a few others will be.

**Comment by emmanuelbernard** [comment]
Will be fixed as part of https://github.com/quarkusio/quarkus/issues/4771

**Comment by gastaldi** [comment]
Looks like this is fixed. Closing

![Screenshot from 2019-11-26 10-09-37](https://user-images.githubusercontent.com/54133/69636313-0fa4ef80-1035-11ea-8c69-92f6f280771c.png)
