### ISSUE TITLE
make sure generation takes into consideration the platform bom/version you are using

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/code.quarkus.io#203]
when generating projects using platform you should make sure platformArtifactId and platformVersion is set as otherwise you won't generate with the right bom and camel dependencies wouldn't be able to resolve.

note: I couldn't verify if the above was already done so opening this to not be forgotten.

**Comment by ia3andy** [comment]
via https://github.com/quarkusio/code.quarkus.io/pull/208
