### ISSUE TITLE
Make default extension more intuitive, it can be percieved as a bug

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/code.quarkus.io#204]
**Describe the bug**
See the following image. The "RESTEasy JAX-RS" extension is always checked and can't be unchecked. It also doesn't appear in the "Selected Extensions" list.

**Screenshots**
![image](https://user-images.githubusercontent.com/51681/68022687-fb234080-fc9c-11e9-9d8c-e61cedaa83bb.png)

**Environment (please complete the following information):**
I've tried this with Chrome 78.0.3904.70 (Official Build) (64-bit) and Safari Version 13.0.3 (14608.3.10.10.1).

**Comment by ia3andy** [comment]
@paulrobinson read the tooltip:
![image](https://user-images.githubusercontent.com/2223984/68024759-4a706d80-fcab-11e9-8f83-597cdb8d1420.png)


But you saying that means we need to find a way to make it more intuitive ;-) So I just rename the bug..

**Comment by paulrobinson** [comment]
I did wonder if it was a default choice. But then, I was confused as it didn't appear in the list to the left and I couldn't remove it.

Would it be more obvious if it behaved the same as the other extensions (i.e could be un-checked and was in the 'Selected Extensions' list)? But, was simply checked by default?

**Comment by ia3andy** [comment]
@paulrobinson wdyt:
![image](https://user-images.githubusercontent.com/2223984/68306033-0d401d00-00a9-11ea-8c4f-b0cb4c167e4e.png)

**Comment by paulrobinson** [comment]
I'm not sure, maybe get @jkbrock's input. I worry that i'm just providing personal opinion/preference. We probably want some real UX input here.

**Comment by ia3andy** [comment]
@paulrobinson those tags are already used for "preview", so UX speaking I think it's alright, I can still ask Jason for sure.
