### ISSUE TITLE
Gradle kotlin project missing all-open plugin

### ISSUE THREAD

**Issue by zulq** [quarkusio/code.quarkus.io#220]
**Describe the bug**
When kotlin is chosen, the all-open plugin is not added

**Expected behavior**
When kotlin is chosen the all-open plugin should be added and the default allOpen section

**Actual behavior**

**To Reproduce**
1. Visit https://code.quarkus.io/
2. Create a new project with kotlin and Gradle as build tool.

**Comment by gsmet** [comment]
Could you create the issue in the main repo there: https://github.com/quarkusio/quarkus ?

**Comment by zulq** [comment]
Done. Should I also do the same for: https://github.com/quarkusio/code.quarkus.io/issues/219 ?

**Comment by edewit** [comment]
@ia3andy this can be closed right? as it's resolved
