### ISSUE TITLE
Add extension version in tooltip

### ISSUE THREAD

**Issue by davsclaus** [quarkusio/code.quarkus.io#230]
**Description**
(Describe the feature here.)

It would be nice to see the version of the extension somewhere on the code.quarkus.io website, for example in the tooltip (and maybe later somewhere else too).

**Comment by ia3andy** [comment]
@maxandersen would that make sense?

**Comment by maxandersen** [comment]
+1 since you are already rendering the tooltips might as well add that detail - maybe visually dimmed/scaled down to not "dominate" the tooltip.
