### ISSUE TITLE
Remove Kafka client from search

### ISSUE THREAD

**Issue by hguerrero** [quarkusio/code.quarkus.io#248]
Preferred way to go with simple Kafka producer and consumers is via Small Rye so, no need to show in the results for `Kafka` the simple client. 

Remove it from search results.

**Comment by ia3andy** [comment]
@emmanuelbernard any thoughts?

**Comment by emmanuelbernard** [comment]
I disagree, what we put in place is to show the SR impl on top. But both have their place as result.
