### ISSUE TITLE
code.quarkus.io should be able to scaffold an extension

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/code.quarkus.io#250]
**Description**

In the spirit of "working code over comprehensive documentation", I'd like to propose that in addition to scaffolding an application, code.quarkus.io should be able to scaffold an extension. 

At first, it should probably just offer a static "hello world" code that you can't customize (except groupId:artifactId etc.). Later, it could offer selecting some common `BuildStep`s (such as provide a `FeatureBuildItem`, provide an `AdditionalBeanBuildItem`, etc.). Not sure if that's really needed.

Of course the generated code should contain tests (including native etc.).

**Comment by ia3andy** [comment]
@Ladicek we have a planned feature really similar to what you are describing ;-)
