### ISSUE TITLE
Add an option to select programming language 

### ISSUE THREAD

**Issue by hantsy** [quarkusio/code.quarkus.io#252]
Add an option to select the supported programming languages, such as Groovy , Kotlin, Scala , Java etc.

**Comment by ia3andy** [comment]
Hi @hantsy you can generate a project with Kotlin and Scala, just pick it in the extension:
![image](https://user-images.githubusercontent.com/2223984/69732571-237f4d00-112c-11ea-8ddd-f21d3fe5cf3c.png)

Please close if this answer your request :-)

**Comment by hantsy** [comment]
It is OK. 
(but I think it is better to provide an option as part of the project info instead of extensions.)

**Comment by ia3andy** [comment]
@hantsy we don't want to have too many options at the top but something more extensible.. thus it is extension..
