### ISSUE TITLE
Allow user select a version from the available versions of Quarkus

### ISSUE THREAD

**Issue by hantsy** [quarkusio/code.quarkus.io#254]
1. All released versions that are under maintain. 
2. A snapshot version for nightly builds
3. All extensions should be labeled with the compatibilities with the versioned Quarkus.  Incompatible versions should be disabled or hidden in the web UI.

**Comment by ia3andy** [comment]
@hantsy this is not planned for the moment as it introduce a lot of complexity for a small benefit. You can still change the Quarkus version in the generated project.
