### ISSUE TITLE
Remove "quarkus-resteasy" as always selected and not able to deselect

### ISSUE THREAD

**Issue by kenfinnigan** [quarkusio/code.quarkus.io#255]
Currently the RESTEasy extension is selected and not removable as a selection.

This is not great is it means anyone creating a messaging type application, such as kafka, that doesn't want an http server has to manually remove the dependency from their generated project. And also be aware that they need to remove the dependency in the first place.

This could be related to the idea of creating stacks, http, messaging, etc, but I think we need to fix this in the short term first.

Also, it would be good if it didn't create a REST endpoint but a messaging method instead

**Comment by gsmet** [comment]
I'm not sure the issue should be created here.

Basically, we need more templates in Quarkus itself because the only one we
have is a RESTEasy one. Once we have that, we could consider making
RESTEasy optional.

**Comment by kenfinnigan** [comment]
Feel free to move wherever necessary, I created here because it was raised as an issue with a generated project from the webpage

**Comment by kenfinnigan** [comment]
@emmanuelbernard should this issue be here or somewhere else?

**Comment by ia3andy** [comment]
I just created an epic for it:
https://github.com/quarkusio/quarkus/issues/8134
