### ISSUE TITLE
openapi generator

### ISSUE THREAD

**Issue by vijaychd** [quarkusio/code.quarkus.io#257]
**Description**
Add a sample openapi spec in https://code.quarkus.io/ to provide generated code using openapi generator for API model and resources when user intends to build Restful API applications.  User can later replace api spec in their environment.  It would help in quick bootstrapping using API first approach.

**Comment by dudash** [comment]
+1 
I'd love it if Quarkus could match the API First approach showcased here:
https://developers.redhat.com/blog/2019/01/14/building-a-node-js-service-using-the-api-first-approach/

**Comment by MrJustreborn** [comment]
+1
With API-First it's easy to just link to your yml to the backend (quarkus) und frontend (angular) and let the generator create the skeleton (or complete code for angular).

**Comment by ia3andy** [comment]
I am not sure the state of this initiative (cc @maxandersen), but we thought it would be better to implement the "api first approach" through an extension using the dev-ui.

The reason behind that preference is that "api first" doesn't mean "only when starting" so an extension is a better fit for this than code.quarkus.io. The user would be able to edit the api and let the code be auto generated during the dev phase.

**Comment by maxandersen** [comment]
See https://github.com/quarkusio/quarkus/issues/3905 for the openapi gen efforts.

**Comment by ia3andy** [comment]
@maxandersen I am not sure this is what I was referring to. I meant the apicurio extension.

**Comment by maxandersen** [comment]
I don't think apicurio happened yet. But there is one doing similar linked to this.
