### ISSUE TITLE
Add link to guide from list of extensions

### ISSUE THREAD

**Issue by davsclaus** [quarkusio/code.quarkus.io#258]
**Description**
(Describe the feature here.)

On the code.quarkus.io website, when you are picking among extensions. Then all you have today as details are a short name, and a tiny summary. 

It would be nice if there was a link somewhere (maybe a book icon before the copy to clipboard icon, on the right hand side), you could click that opens a new browser tab, and goes to the guide of the extension (if a guide exists). Where you can read more details about what it does etc.

**Comment by ia3andy** [comment]
Thanks for the feedback @davsclaus that would indeed be great. This is planned for very soon ;-)
