### ISSUE TITLE
Select all extensions from a category

### ISSUE THREAD

**Issue by jeffmaury** [quarkusio/code.quarkus.io#262]
**Description**

Would be nice if we could select all extensions from a category instead of having to select each extension from the category

**Comment by ia3andy** [comment]
@jeffmaury do you have an example use case where it's useful to select the whole category?

**Comment by jeffmaury** [comment]
Wanted to generate an application with all extensions but I admit this is a special case.
But if you're a Camel used, you wight want to get all Camel Extension then go the Integration and select all extensions

**Comment by ia3andy** [comment]
@jeffmaury we have a discussion on something similar that might make creating an app easier:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/quarkus-dev/Ejw1Hl6tcYg/CEspbweSBAAJ
