### ISSUE TITLE
Handle new "experimental" flag

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#264]
**Description**
Handle new "experimental" flag

@emmanuelbernard I need the tooltip text for it.

Preview text is: "This is work in progress. API or configuration properties might change as the extension matures. Give us your feedback :)"

**Comment by emmanuelbernard** [comment]
Early feedback is requested to mature the idea. There is no guarantee of stability nor long term presence in the platform until the solution matures.
