### ISSUE TITLE
Provide a way to open Code Quarkus with pre-selected extensions and infos

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/code.quarkus.io#270]
I'd like to have a way so I can share a link to code.quarkus.io which lets people easily get a new project with extensions I have pre-chosen for them. E.g. to get them started quickly with KafkaStreams and Health and Metrics, without having to tell them "Check extensions A, B, C".

E.g. it could be done via allowing to call the page with values pre-selected based on query parameters.

**Comment by ia3andy** [comment]
just so you know, you can already share the link that you have when generating an app, ex:
https://code.quarkus.io/api/download?g=org.acme&a=test-link&v=1.0.0-SNAPSHOT&b=MAVEN&c=org.acme.ExampleResource&e=io.quarkus%3Aquarkus-smallrye-jwt&e=io.quarkus%3Aquarkus-hibernate-validator&e=io.quarkus%3Aquarkus-resteasy-jackson&cn=code.quarkus.io

**Comment by gunnarmorling** [comment]
Ah, thanks, that's cool, didn't know that. Is there any way to get hold of
such link?

>

**Comment by ia3andy** [comment]
![image](https://user-images.githubusercontent.com/2223984/70921565-d3a5ee80-2024-11ea-8c82-452faa27e798.png)

Sorry it's in french :-p

FYI: We will soon provide a way to get this link without the need to generate the app (from the main screen)..

**Comment by gunnarmorling** [comment]
Ok, sweet. That sounds good. Thanks a lot!

>
