### ISSUE TITLE
Fix the hardcoded versions

### ISSUE THREAD

**Issue by gsmet** [quarkusio/code.quarkus.io#273]
In https://github.com/quarkusio/code.quarkus.io/pull/272 , I had to hardcode the versions because of a cryptic issue with configuration.

It needs to be fixed before the next release.

**Comment by ia3andy** [comment]
This has been fixed by https://github.com/quarkusio/code.quarkus.io/commit/ad2cb79fb086b71792145bdc50e46e4e9deaae4d
