### ISSUE TITLE
Start coding / Generate your application fails with "Invalid shortId:"

### ISSUE THREAD

**Issue by michael-schnell** [quarkusio/code.quarkus.io#283]
1. Goto https://code.quarkus.io/
2. Press "Generate your application"
3. Error message "Invalid shortId:" appears with this page: https://code.quarkus.io/d?g=org.acme&a=code-with-quarkus&v=1.0.0-SNAPSHOT&b=MAVEN&c=org.acme.ExampleResource&s=&cn=code.quarkus.io

Downloading the ZIP is not possible.

![screenshot](https://user-images.githubusercontent.com/1856319/72814932-2eef8000-3c66-11ea-91f0-2f4fc9f30be6.png)

**Comment by ia3andy** [comment]
@geoand yes, I am on it ;-)

**Comment by geoand** [comment]
Thanks

**Comment by ia3andy** [comment]
This fix will be available in production in ~15mins

**Comment by geoand** [comment]
Thanks a lot for the super quick response!

**Comment by ia3andy** [comment]
Thank you very much @michael-schnell for reporting it with those detailed infos!

**Comment by ia3andy** [comment]
The link above is now working again.. sorry for the inconvenience.
