### ISSUE TITLE
Installing the Intellij plugin for Quarkus tools in breaking spring application.properties

### ISSUE THREAD

**Issue by vinchauhan** [quarkusio/code.quarkus.io#289]
**Describe the bug**
Quarkus Intellij plugin is making spring projects created from Intellij  start.spring.io plugin not working as application.properties is loosing autocompletion.

**Expected behavior**
Spring projects application.properties shouldnt be affected.
**Actual behavior**
The application.properties are loosing spring autocompletion as well as an lts folder is created on the root which application.properties_error.log

**To Reproduce**
1. Install the Quarkus tools from Intellij plugin website or IDE
2. Create a spring project from Intellij IDE using start.spring.io
3. The application.properties are loosing spring autocompletion as well as an lts folder is created on the root which application.properties_error.log

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Browser: 
 - OS: 

**Additional context**
(Add any other context about the problem here.)

**Comment by ia3andy** [comment]
@maxandersen any thoughts?

**Comment by maxandersen** [comment]
this should be reported here: https://github.com/redhat-developer/intellij-quarkus/issues - I've created https://github.com/redhat-developer/intellij-quarkus/issues/51 as a copy.

Not sure what can be done to deal with this though; the reverse is true too - installing spring support would break quarkus tooling. Annoying problem of using same name. lets discuss on the other bug though.
