### ISSUE TITLE
Cannot remove extensions by unchecking checkbox

### ISSUE THREAD

**Issue by kevcodez** [quarkusio/code.quarkus.io#290]
**Describe the bug**
On the Quarkus project generator, after adding an extension by clicking on a checkbox, unchecking the checkbox will *not* remove that extension.

**Expected behavior**
When unchecking the checkbox, the extension will be removed from the list of selected extensions.

**Actual behavior**
Unchecking does nothing.

**Environment (please complete the following information):**
 - Browser: Chrome 79 
 - OS: Win 10

**Comment by ia3andy** [comment]
Indeed, good catch, I am on it 👍

**Comment by ia3andy** [comment]
Production is now updated with the fix..
