### ISSUE TITLE
initial setup instructions are outdated

### ISSUE THREAD

**Issue by evanchooly** [quarkusio/code.quarkus.io#293]
**Describe the bug**
Once the zip file is generated and ready for download, the instructions say to run `mvn compile quarkus:dev` still.  The `compile` is no longer necessary.

**Expected behavior**
It should only say `mvn quarkus:dev`.

**Comment by ia3andy** [comment]
Ahh cool, I didn't know that :-)

**Comment by ia3andy** [comment]
@evanchooly maybe you can provide a PR, it's an easy fix (Just look for `mvn compile quarkus:dev` in the code)
