### ISSUE TITLE
Add the option to automatically create a GitHub repository with the application content

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#3]
Let's discuss how to make this xp as painless as possible for the user.

We have this feature in the Launcher and all the authorization dance is a bit heavy. Let's try to find ideas on another approach to deal with this?

BTW it may be nice to provide an external service whose job is to import zip as a new repository in any git provider (github, bitbucket, gitlab...), I guess many people might like such a service. Any web-app just send the user to this page with a link to the zip ( `git-import.io/?zip=http://...my-app.zip`), the user is then directed toward configuring the import..

**Comment by maxandersen** [comment]
do we really need/want this buitin to code.quarkus.io ? seems like unnecessary complexity to me.

external service sounds like nice side project though ;)

**Comment by edewit** [comment]
@maxandersen unlike the one we had on Launcher this one will be really simple. Just authorize and push a button

**Comment by ia3andy** [comment]
@maxandersen we nearly have it available:
https://github.com/quarkusio/code.quarkus.io/pull/227

@FroMage was the initiator of this feature request.

IMO, there will be not added complexity for the enduser it will be just a secondary option in the generate dropdown (that will appear soon). Having your project directly on GH ready to code is kinda cool I think :)

**Comment by ia3andy** [comment]
@maxandersen what if you want to start working on a Quarkus new service with your friend, ...

**Comment by maxandersen** [comment]
> @maxandersen unlike the one we had on Launcher this one will be really simple. Just authorize and push a button

that is good - is it done all client side or more to it ?

**Comment by maxandersen** [comment]
> @maxandersen what if you want to start working on a Quarkus new service with your friend, ...

I know how to do git push :)

**Comment by ia3andy** [comment]
@maxandersen but first you need to create a repo

**Comment by edewit** [comment]
There needs to be a service on the backend to push the code

**Comment by maxandersen** [comment]
> IMO, there will be not added complexity for the enduser it will be just a secondary option in the generate dropdown (that will appear soon). Having your project directly on GH ready to code is kinda cool I think :)

Don't get me wrong, I grok the "coolness" of it and I like the prospect of more quarkus projects showing up on quarkus....

what i'm less fan of is "a lot of 1-of-generated projects showing up on github with no real value" and what about gitlab, etc.  it adds noise/complexity.

But if you guys are sure this is simple, won't break easily and trivial to do sure - sounds good ;)

**Comment by edewit** [comment]
Well it should be a starting point for your the rest of your application, of course we can't force people to do something with it, but on the other hand I wouldn't let something sit on github if I didn't plan to do something with it at some point.

**Comment by maxandersen** [comment]
> I wouldn't let something sit on github if I didn't plan to do something with it at some point.

dont go looking at my 200+ repos :)

in any case after a chat today @ia3andy and I came up with some interesting future enhancemetns that is made nicer by having the github step like a "open in che" badge or "deploy to openshift" etc.

**Comment by edewit** [comment]
Also #33 will make more sense when a github create is there
