### ISSUE TITLE
Easy way to download Quarkus quickstart projects

### ISSUE THREAD

**Issue by xorye** [quarkusio/code.quarkus.io#301]
**Description**
It would be cool if there was a way to select a Quarkus quickstart project from this repository: https://github.com/quarkusio/quarkus-quickstarts to download.

With something like this, I could quickly choose a sample project and experiment with it right away without having to git clone (but maybe there's a better way?).

**Comment by ia3andy** [comment]
I guess that could help :-): http://kinolien.github.io/gitzip/

**Comment by ia3andy** [comment]
You just have to copy past the url of the folder and hit Download (no need to enter a token)

**Comment by ia3andy** [comment]
@emmanuelbernard @gsmet maybe I could add an endpoint on the code.quarkus.io/api? That we could reference from the a page on the website?

**Comment by emmanuelbernard** [comment]
what would the UI look like?

**Comment by ia3andy** [comment]
> what would the UI look like?

@emmanuelbernard  I would see it similar to this:
![image](https://user-images.githubusercontent.com/2223984/75157291-1c101580-5714-11ea-9f17-25611fc954a5.png)

Instead of extension, you have quickstarts, and in the menu you have:
- Open in GitHub
- Copy the command to clone it
- Download as a zip

**Comment by emmanuelbernard** [comment]
Where would it live?

**Comment by ia3andy** [comment]
My first idea would be something like: code.quarkus.io/examples (in the idea of start coding with examples). 
We could also have quickstart.quarkus.io or quarkus.io/quickstart but my concern would be that the naming is really close to code.quarkus.io and could be confusing..

**Comment by ia3andy** [comment]
I don't know if you read it already in the mailing, but I would like to integrate a new panel to have links to all the way to start coding:
- IDE plugins
- Maven Gradle plugins
- The different build of quarkus (and their own coder).. `
- and maybe.. this new page.

I don't yet have the perfect UX in mind, but let's first see if such a feature would be a good addition for the user?

**Comment by emmanuelbernard** [comment]
I guess I would need a visual representation of how people would discover and flow. I don't think a dedicated quickstart property is worth its weight in additional links and complexities.
