### ISSUE TITLE
code.quarkus.io hangs (see screenshot)

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/code.quarkus.io#306]
It's the second time I ran into this issue. Last time was a few months ago. It's hard to reproduce.

What's the user experience?
After not visiting code.quarkus.io for a few weeks, I visited it again. It hangs. The "start screen" of code.quarkus.io doesn't disappear. The blue icon on the white background sticks around forever. Below a screenshot, with the JS console open.

This is on a very stable internet connection (glassfiber) with Chrome. Hitting F5 refresh fixes it, but **a normal user might not try that and just give up using this as it doesn't "just work"**:

![Screenshot](https://user-images.githubusercontent.com/176880/75794402-08e2f280-5d71-11ea-89bc-a317ffdf3e6b.png)

How to reproduce? Maybe this works:
- Go to code.quarkus.io. Don't not visit again later.
- Wait until a new Quarkus version is released, including an update to that website.
- Go to code.quarkus.io, same browser as last time. Don't press F5.

If that reproduces, it seems like the index.html is cached too long?

**Comment by ge0ffrey** [comment]
This clearly proves that it's a caching issue. Probably a bug in the server.

![Selection_277](https://user-images.githubusercontent.com/176880/75795613-d9cd8080-5d72-11ea-988d-f742eabfb5e9.png)

**Comment by gsmet** [comment]
I think the index page should probably not be cached at all. I would expect it to be very small and everything in external resources so it should be sustainable.

**Comment by ia3andy** [comment]
This but is supposed to be fixed :-/

If you look the index is not cached:
![image](https://user-images.githubusercontent.com/2223984/75799762-cd4c2680-5d78-11ea-8894-ca2f8d3a3f6a.png)

@ge0ffrey how long did you wait between the refresh? I fixed it a few months ago..

**Comment by ge0ffrey** [comment]
@ia3andy Hard to say. Just realized: I visited that website like a month ago too, but I use Firefox normally, so that fact that I had it in Chrome yesterday could mean it's been months.

Given that the "before refresh" contained the string `main.f710b5db.chunk.css`, you can probably look through the history of `gh_pages` to figure the exact revision I was looking at, giving you a date. I tried doing that here in the GitHub UI, but there is no `gh_pages` tag. Not sure if it's worth the trouble. I am ok with just closing this presuming it's already fixed until proven otherwise again.
