### ISSUE TITLE
Restrict the remove link to the trash bin

### ISSUE THREAD

**Issue by gsmet** [quarkusio/code.quarkus.io#32]
Right now, the right part behaves like this:
- if you pass over the name of a selected extension, you have a tooltip with the description and if you click, you remove it
- if you pass over the trash bin, you don't have any tooltip and if you click, you remove it

I would lean towards the following behavior:
- over the name of the selected extension: help cursor + description in tooltip, no action on click (or only display the tooltip when clicking)
- over the trash bin, standard action cursor, tooltip stating it will remove the extension, removing on click

**Comment by ia3andy** [comment]
@emmanuelbernard @jasonbrock any opinion?

**Comment by emmanuelbernard** [comment]
yes I got mildly confused by that one too. But no strong opinion. My concern is that the trash area would be a bit small.
