### ISSUE TITLE
Agroal

### ISSUE THREAD

**Issue by mbronshteyn** [quarkusio/code.quarkus.io#323]
**Describe the bug**
Trying to generate sample app with Agroal and Postgres.  Instead I get basic app with REST 'hello'

**Expected behavior**
I expect have an app to have samples on how to use Agroal DataSource with Postgres client

**Actual behavior**
Basic app with no extra features

**To Reproduce**
1.  Pick Agroal DataSource and Postgres 
2. Generate
3. No extra features

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Browser:  Chrome
 - OS: MacOS

**Additional context**
(Add any other context about the problem here.)
<img width="388" alt="Screen Shot 2020-03-24 at 11 11 01 AM" src="https://user-images.githubusercontent.com/27588667/77461824-64c4f800-6dc0-11ea-817d-299aff2d08f4.png">

**Comment by ia3andy** [comment]
I know! That would be such a great feature!! But we don't support it yet, this is part of a larger feature that we definitively want: https://github.com/quarkusio/quarkus/issues/8134

Until then, you can use the different quickstarts we provide: https://github.com/quarkusio/quarkus-quickstarts/
Also we have several guides which could help you: https://quarkus.io/guides/
