### ISSUE TITLE
Redirect "start.quarkus.io" to "code.quarkus.io"

### ISSUE THREAD

**Issue by jclingan** [quarkusio/code.quarkus.io#327]
**Description**
Spring developers are increasingly evaluating and using Quarkus. Their natural expectation is that "start.quarkus.io" is the URL project generation. Having "start.quarkus.io" redirect to "code.quarkus.io" will better meet Spring developer expectations.

**Comment by ia3andy** [comment]
I started the process to create those redirections:
- start.quarkus.io
- launch.quarkus.io

**Comment by ia3andy** [comment]
It is now effective :-)
