### ISSUE TITLE
Multiple entries of "Camel Quarkus Zipfile"

### ISSUE THREAD

**Issue by xorye** [quarkusio/code.quarkus.io#328]
Go to https://code.quarkus.io/ and scroll to the bottom of the "Integration" section.
There are three entries of "Camel Quarkus Zipfile".

![image](https://user-images.githubusercontent.com/20326645/77691370-27f13080-6f7b-11ea-8351-eb32134b074b.png)

**Expected behavior**
There should not be duplicate names

EDIT: from my observations, they seem to be different extensions as they have different artifactIds

**Comment by gsmet** [comment]
@lburgazzoli I would say it's probably an issue in Camel Quarkus? Maybe metadatas that are incorrect?

**Comment by lburgazzoli** [comment]
@ppalaga @jamesnetherton mind having a look ?

**Comment by jamesnetherton** [comment]
This actually got fixed today https://github.com/apache/camel-quarkus/pull/986.

**Comment by rsvoboda** [comment]
@gsmet I noticed that yesterday and fixed that in the mentioned PR.

From the https://github.com/quarkusio/quarkus-platform perspective this will be solved with 1.4 release

Can we do something about quarkus-platform for 1.3.1.Final release? Metadata are used "as is" or can be some tweaking applied?

**Comment by ppalaga** [comment]
This issue was fixed weeks ago and can be closed.

**Comment by gsmet** [comment]
@ppalaga could you check if it's fixed in the version of Camel Quarkus we will use for 1.5? Because I added a workaround in the platform and, if so, I could remove it.

**Comment by ppalaga** [comment]
Yes, it is fixed. I just checked.
