### ISSUE TITLE
Implement Mobile design

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#33]
https://xd.adobe.com/spec/2177f367-4c93-4465-6e62-112ab315eb6e-5746/

**Comment by FroMage** [comment]
I think that feature is a lot less important because very few people will create their apps on their mobile devices.

**Comment by ia3andy** [comment]
Work has been done on mobile to make the layout nicer, I think we don't need more in the near future. We can always re-open if needed..
