### ISSUE TITLE
Better search over components name (for Integration and Camel) 

### ISSUE THREAD

**Issue by dmvolod** [quarkusio/code.quarkus.io#338]
**Description**
The all Camel Quarkus components contains Quarkus name between Camel and component name.
It wold be nice to organize search against comment or change name from 
for example: **Camel Quarkus Azure** to **Camel Azure for Quarkus** or remove Quarkus as for others non-integration components.

**Comment by ppalaga** [comment]
The Camel extension names do not contain "Quarkus" anymore. Also a change was merged today to include description in the scope of the search https://github.com/quarkusio/code.quarkus.io/pull/356
I think this issue can be close.
