### ISSUE TITLE
Please add support for an older version.

### ISSUE THREAD

**Issue by SetoKaiba** [quarkusio/code.quarkus.io#347]
**Description**
Everytime after an update, there's some changes in the template project is not covered in the migration guide.
It would be better if I can generate for an older version. Then I can use the compare tools to compare the changes.

**Comment by SetoKaiba** [comment]
Does anyone read the issues?

**Comment by gsmet** [comment]
Yeah, we do. I'm not sure what the plan is for that one. It's easier said than done though as we don't version the template files right now.

**Comment by ia3andy** [comment]
At some point, it will be available. I also think this is a problem, until we provide a better solution, you can look at the change here (for java):
https://github.com/quarkusio/quarkus/commits/master/devtools/platform-descriptor-json/src/main/resources/templates/basic-rest/java/pom.xml-template.ftl

**Comment by ia3andy** [comment]
Done! (will soon be in prod)
