### ISSUE TITLE
Making code.quarkus.io compatible with the registry

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/code.quarkus.io#352]
This depends on the work done in https://github.com/quarkusio/quarkus/issues/9294. 

Code.quarkus.io should use the extension registry instead of relying on a single platform/release.

**Comment by gastaldi** [comment]
@ia3andy registry.quarkus.io is online. Let me know if you need any assistance in this one

**Comment by ia3andy** [comment]
I guess we can close this since code.quarkus.io will use @aloubyansky api starting from 1.13?

**Comment by gastaldi** [comment]
@ia3andy Is code.quarkus.io already using the registry client API in staging?

**Comment by ia3andy** [comment]
@gastaldi no it's waiting for 1.13 (in the `next` branch) as the new client api will be released with it:
https://github.com/quarkusio/code.quarkus.io/commits/next

At some point I will create a staging for the next branch :)

**Comment by gastaldi** [comment]
Ok, then I can guess this issue can be closed when the new client API is being used in production 😉
