### ISSUE TITLE
Enable an easier way to run mvnw on IDEs such as NetBeans

### ISSUE THREAD

**Issue by manoelcampos** [quarkusio/code.quarkus.io#353]
The [code.quarkus.io](https://code.quarkus.io) website is great for generating a project.
But running the project in the dev environment requires the command 
```bash
./mvnw compile quarkus:dev
```

That means the project cannot be run by just clicking the "Play" button on the IDE.
For NetBeans, I've been using the `exec-maven-plugin` as below and it works right away.
It's probably not the best way to do that because it uses `mvn` to run the maven wrapper.
But it reduces the entry barrier for developers used to just click the "Play" button on IDEs.
Since I'm using Quarkus with my students, that makes their life easier.
Therefore, I'm wondering if the project generated at [code.quarkus.io](https://code.quarkus.io) could include something like that.

```xml
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>exec-maven-plugin</artifactId>
  <version>1.6.0</version>
  <configuration>
    <executable>./mvnw</executable>
    <arguments>
      <argument>clean</argument>
      <argument>compile</argument>
      <argument>quarkus:dev</argument>
    </arguments>
  </configuration>
</plugin>
```

**Comment by ia3andy** [comment]
@maxandersen any insight?

**Comment by manoelcampos** [comment]
Another issue by using exec-maven-plugin is that if it's Windows, the command is `./mvnw.cmd`, otherwise it's `./mvnw`.

**Comment by maxandersen** [comment]
so there is no requirement to use "./.mvnw" you could just use a mvn as installed in your IDE or globally on the system. 

I'm surprised that doesn't actually just work ? 

btw. not exactly the same but one thing I use is https://github.com/dansomething/mdub which will use global mvn if no ./mvnw available ...i wonder if that could help you here ?

**Comment by manoelcampos** [comment]
Thanks @maxandersen. 
I didn't know we could simply use mvn. The [guides](https://quarkus.io/guides/getting-started#running-the-application) just say to use mvnw.

In that case, I think adding maven-exec-plugin when generating a project at code.quarkus.io makes sense and it will be easer to run the project from an IDE.

What do you think?

**Comment by maxandersen** [comment]
isn't "Play" in the IDE supposed to run the actual app and not dev mode?

**Comment by manoelcampos** [comment]
In NetBeans or IntelliJ, the play button doesn't work for Quarkus projects if you don't change project run settings, for instance by adding the maven-exec-plugin. I don't know in Eclipse.

**Comment by manoelcampos** [comment]
I could change the project generation to include the maven-exec-plugin if you are ok with it.

**Comment by manoelcampos** [comment]
In Netbeans, the run button is disabled until you set the run configuration.
<img width="795" alt="Screen Shot 2020-08-03 at 10 04 23" src="https://user-images.githubusercontent.com/261605/89185605-e3048880-d570-11ea-9b69-e17763de1b64.png">

**Comment by manoelcampos** [comment]
In NetBeans, the run button doesn't work until the run configuration is set.
![quarkus](https://user-images.githubusercontent.com/261605/89187293-763ebd80-d573-11ea-9d39-0d400625ee2a.gif)

**Comment by maxandersen** [comment]
I get that. But that's why I ask - Is the run button not for running the app rather than start in dev mode. 

What does debug do ?

**Comment by manoelcampos** [comment]
> I get that. But that's why I ask - Is the run button not for running the app rather than start in dev mode.

Yes, it is. But it doesn't work anyway.

> What does debug do ?

It simply doesn't work either. The behavior is the same as the gif I showed.

**Comment by maxandersen** [comment]
I mean what does it do fir ordinary maven projects?

**Comment by manoelcampos** [comment]
The play button runs the project in an Application Server. The debug button starts debugging in that configured AS.

**Comment by maxandersen** [comment]
which mvn tasks does it run for that ?

**Comment by manoelcampos** [comment]
The command executed by NetBeans in a regular JavaEE app running in some AS is:

```bash
mvn -Dnetbeans.deploy=true package
```

For debug it is:

```bash
mvn -Dnetbeans.deploy.debugmode=true -Dnetbeans.deploy=true package
```

**Comment by manoelcampos** [comment]
But it just enables the run and debug buttons if an AS is configured, which doesn't apply for Quarkus projects.

**Comment by maxandersen** [comment]
Neither of those mvn commands actually runs or deploy anything....unless netbeans does some additional magic...

**Comment by manoelcampos** [comment]
By default, the command is just that, which fires other maven plugins, namely: maven-dependency-plugin, maven-compiler-plugin, maven-resources-plugin, maven-surefire-plugin and then maven-war-plugin. 
Some plugin probably just copies the generated war to the deploy directory inside the AS.
The complete log is below. But this entire process is not relevant for Quarkus projects because the way to run them is totally different. That is why I suggested to just add the maven-exec-plugin that solves the problem.


```bash
cd /tmp/mavenproject1; JAVA_HOME=/Users/manoelcampos/.sdkman/candidates/java/11.0.8-zulu "/Applications/NetBeans/Apache NetBeans 12.0.app/Contents/Resources/NetBeans/netbeans/java/maven/bin/mvn" -f /tmp/mavenproject1/pom.xml clean install
Scanning for projects...

--------------------< com.mycompany:mavenproject1 >---------------------
Building mavenproject1-1.0-SNAPSHOT 1.0-SNAPSHOT
--------------------------------[ war ]---------------------------------

--- maven-clean-plugin:2.5:clean (default-clean) @ mavenproject1 ---

--- maven-dependency-plugin:2.6:copy (default) @ mavenproject1 ---

--- maven-resources-plugin:2.6:resources (default-resources) @ mavenproject1 ---
Using 'UTF-8' encoding to copy filtered resources.
Copying 1 resource

--- maven-compiler-plugin:3.1:compile (default-compile) @ mavenproject1 ---
Changes detected - recompiling the module!
Compiling 2 source files to /tmp/mavenproject1/target/classes

--- maven-resources-plugin:2.6:testResources (default-testResources) @ mavenproject1 ---
Using 'UTF-8' encoding to copy filtered resources.
skip non existing resourceDirectory /tmp/mavenproject1/src/test/resources

--- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ mavenproject1 ---
No sources to compile

--- maven-surefire-plugin:2.12.4:test (default-test) @ mavenproject1 ---
No tests to run.

--- maven-war-plugin:2.3:war (default-war) @ mavenproject1 ---
Packaging webapp
Assembling webapp [mavenproject1] in [/tmp/mavenproject1/target/mavenproject1-1.0-SNAPSHOT]
Processing war project
Copying webapp resources [/tmp/mavenproject1/src/main/webapp]
Webapp assembled in [88 msecs]
Building war: /tmp/mavenproject1/target/mavenproject1-1.0-SNAPSHOT.war

--- maven-install-plugin:2.4:install (default-install) @ mavenproject1 ---
Installing /tmp/mavenproject1/target/mavenproject1-1.0-SNAPSHOT.war to /Users/manoelcampos/.m2/repository/com/mycompany/mavenproject1/1.0-SNAPSHOT/mavenproject1-1.0-SNAPSHOT.war
Installing /tmp/mavenproject1/pom.xml to /Users/manoelcampos/.m2/repository/com/mycompany/mavenproject1/1.0-SNAPSHOT/mavenproject1-1.0-SNAPSHOT.pom
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time:  9.763 s
Finished at: 2020-08-10T11:17:20-03:00
------------------------------------------------------------------------
```

**Comment by manoelcampos** [comment]
Any thoughts on that?
