### ISSUE TITLE
Pass a search query via URL parameter

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/code.quarkus.io#357]
We have a search field with `id="extension-search"` but typing something like https://code.quarkus.io/?extension-search=camel in an address line of a browser does not bring a filtered list of extensions.

This might be handy when I want to point somebody to a specific extension in a chat on in a blog post.

Another variant of this could be to support selecting multiple specific extensions, something like: https://code.quarkus.io/?select=quarkus-resteasy-jackson,camel-quarkus-timer,camel-quarkus-http
That would also be handy when writing a guide or blog post about some specific combination of extensions.

**Comment by ia3andy** [comment]
Have you tried the share feature?
![image](https://user-images.githubusercontent.com/2223984/84405761-ddda2b80-ac08-11ea-8dc4-1e7d9ebf9cab.png)

Here is an example:
https://code.quarkus.io/?g=org.acme&a=code-with-quarkus&v=1.0.0-SNAPSHOT&b=MAVEN&c=org.acme.ExampleResource&s=pV1.ekA.d7W.Q3z&cn=code.quarkus.io

**Comment by ppalaga** [comment]
Yeah, thats's great for the second use case. Thanks, I did not know about that. BTW, if the URL in the browser was in sync with the state of the app, the feature would perhaps be easier to discover and more intuitive to use - I'd have just to copy the URL.

The first use case (filter via URL) is slightly different and I still think it would be useful.

**Comment by ia3andy** [comment]
@ppalaga thanks to @RubensKj we now have https://code.quarkus.io/?extension-search=camel

**Comment by ppalaga** [comment]
Perfect, thanks!

Keeping the URL in sync with the state of the app (so that it is easier to discover the supported query params) is the last one on my wish list :)

**Comment by RubensKj** [comment]
Hello @ppalaga, I'll look about this sync with state of the app and URL. I think that is better to discover the supported query params too

**Comment by ia3andy** [comment]
@ppalaga your wish has come true thanks to @RubensKj :)

**Comment by ppalaga** [comment]
I love it @RubensKj !
