### ISSUE TITLE
Provide a "Maven-Strategy" for application generation

### ISSUE THREAD

**Issue by janmaterne** [quarkusio/code.quarkus.io#366]
At the moment the menu "Generate your application" provides three items/generation strategies:

- Download as a zip
- Push to GitHub
- Share

Provide a new "Maven" which generates the Maven command for setting up the project and copy the command to the clipboard.

**Comment by ia3andy** [comment]
Hey @janmaterne, TBH I have thought about it for a while, but then I thought it wouldn't bring that much. Do you have a scenario where it would be better (quicker) than generating the zip or pushing to github?

**Comment by janmaterne** [comment]
Github is a no go for inhouse projects. Download is less good if you have to describe your doing. Local generating the code is ok.

**Comment by ia3andy** [comment]
Ok, noted! I'll see if we can make it happen :)

**Comment by janmaterne** [comment]
Could be related to #186

**Comment by ia3andy** [comment]
Yes, closing this one in favor of the other. I am a bit busy those days, I'll implement it asap..
