### ISSUE TITLE
Support creating extensions

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/code.quarkus.io#369]
**Description**
Besides creating apps, it would be nice if code.quarkus.io created Quarkus extensions

**Comment by ia3andy** [comment]
@gastaldi in the codestart I am implementing, we can provide different project base, for now: `quarkus`, we could add `quarkus-extension` in the future :)

**Comment by ia3andy** [comment]
https://github.com/quarkusio/quarkus/issues/11130

**Comment by ia3andy** [comment]
I don't think this will be available from code.quarkus.io, only from the quarkus CLI tools
