### ISSUE TITLE
CI builds to ensure code.quarkus keep up with core quarkus 

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/code.quarkus.io#375]
**Description**
We've had a few times now that Quarkus release got affected by code.quarkus not being aligned with quarkus core.

Should make code.quarkus participate in [quarkus ecosystem ci](https://github.com/quarkusio/quarkus-ecosystem-ci) so we at least know when it is failing.

**Comment by ia3andy** [comment]
This is indeed something we must have!

**Comment by ia3andy** [comment]
done: https://github.com/quarkusio/quarkus/issues/11515
