### ISSUE TITLE
move to java ?

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/code.quarkus.io#376]
**Description**
With issues like #375 it is more and more important we are able to fix code.quarkus app quickly.

Either those with kotlin skills volunteer to maintain it on the fly all the time; or we move to java and can see others help more easily.

**Comment by ia3andy** [comment]
My opinion is that we should look at the result. We didn't have any down time and almost no problem on production for almost a year.

The problem @gsmet met on Thursday was detected at build/test time because catalog compatibility is verified (It was just a matter of normalizing the type which input in different forms)

IMHO it's really easy to blame the language or the codebase, I know some companies that use multiple languages for different micro-services without any problem. I would blame personally blame the fact that we:
- Have no way to make sure the Quarkus build is compatible before the last second..
- Have to release it the day before a 3 days WE and outside normal EU working hours..

I also think we should find 1-2 Kotlin "Happy" people who could be my backup in case of bugs.

We also should note that looking at stats, Kotlin is in our top 15 extensions. thanks to code.quarkus.io in Kotlin, we have already detected bugs in early stages, and other bugs that would have been found by customers. 

I know Kotlin is not always favored by some, but it's a Quarkus feature that we provide, plus taking into account all the above, I think it would be a real shame to rewrite this code in Java...

**Comment by ia3andy** [comment]
BTW, on that road, 80% of code.quarkus.io is frontend (typescript + react), who is going to fix bugs in it? Java would not change this..

**Comment by FroMage** [comment]
> we are able to fix code.quarkus app quickly.

> Either those with kotlin skills volunteer to maintain it on the fly all the time; or we move to java and can see others help more easily

Sounds to me like we rather have a problem with not having a team (can't be a single person) responsible for being on-call and ready to respond to monitoring in case this service goes down, with the expertise to fix it ASAP and redeploy it, or mitigate.

That's quite a different role than just software maintainer, and is not necessarily related to the language.

BTW this does not sound like a community issue, because the community is not responsible for downtime ATM.

**Comment by maxandersen** [comment]
I tried to separate the discussions about language vs the lack of CI/early testing by opening this separately from #375 and please note it has a big question mark at the end.

@ia3andy I do not understand what "Have no way to make sure the Quarkus build is compatible before the last second" means; can you please put info on #375 what that refers to since afaics building and testing code.quarkus is just as easy as any other thing that exists outside quarkus.

Same with "Have to release it the day before a 3 days WE and outside normal EU working hours." - this should just not be an issue. It should be our goal to update and ship code.quarkus at anytime / anywhere optimally by anyone. Again, lets keep that discussion to #375. 

"I know some companies that use multiple languages for different micro-services without any problem"

I know companies that stopped doing multiple languages because to ensure they kept focussed on what was important rather than arguing over language choices :)  (tounge in cheek - but I hope you get my point that other teams success or failures on this doesn't really matter)

"I also think we should find 1-2 Kotlin "Happy" people who could be my backup in case of bugs."
- for me it seems easier to fix the underlying issues (primarily #375). If we can find happy kotlin users then thats fine too. 

"BTW, on that road, 80% of code.quarkus.io is frontend (typescript + react), who is going to fix bugs in it? Java would not change this" 

1) typescript + react rarely if ever requires custom setup to fix
2) these historically haven't had compile/build issues preventing an update

"BTW this does not sound like a community issue, because the community is not responsible for downtime ATM." 

I'll disagree on that one - This isn't really about downtime IMO, its more about what it makes sense for us to invest/work on and it affects community if code.quarkus isn't readily available. If there are community members that can help on this thats great.

For me the only valid reason that are listed is the value of having an example driving/validating kotlin features. That is a help and I used it as an example my self before but if we can't maintain or have proper CI for code.quarkus that has to get fixed - no matter the language.

**Comment by FroMage** [comment]
> > "BTW this does not sound like a community issue, because the community is not responsible for downtime ATM."

> I'll disagree on that one - This isn't really about downtime IMO, its more about what it makes sense for us to invest/work on and it affects community if code.quarkus isn't readily available. If there are community members that can help on this thats great.

I mean that this is an uptime/reliability issue, and the service is provided by RH, not the community, ATM, and so we should be having the discussion about uptime and on-call duty and responsibility. This is a role that is typically compensated for, BTW, where people who are on call duty are not allowed to be away from keyboard further than X minutes and can't drink, in most cases I know of.

I think it's unfair to expect this service to fall on a single guy without it having been discussed (forgive me if it has), and it's unrealistic to think a single person can be on-call always without rotation.

So IMO this is the discussion we should be having: who's the on-call team, how do they synchronise, what's the procedure for emergency fixes, how do they get compensated for the extra constraints?

When you figure out how's that team, then you can ask them if they want to switch to Java.

**Comment by ia3andy** [comment]
> @ia3andy I do not understand what "Have no way to make sure the Quarkus build is compatible before the last second" means; can you please put info on #375 what that refers to since afaics building and testing code.quarkus is just as easy as any other thing that exists outside quarkus.

Sorry I have not be clear, I just meant that we currently don't have such a verification, we should of course discuss it and implement something (whatever the language)

**Comment by ia3andy** [comment]
> "BTW, on that road, 80% of code.quarkus.io is frontend (typescript + react), who is going to fix bugs in it? Java would not change this"
> 
> 1. typescript + react rarely if ever requires custom setup to fix
> 2. these historically haven't had compile/build issues preventing an update

This is right, and make me think about a possible middle ground to make everyone happy. So as you said, the problem for releases would mostly be in the interface between the Quarkus platform and code.quarkus.io. We can have `.java` in a kotlin project, so let's rewrite that interface in java?

WDYT?

**Comment by maxandersen** [comment]
> > > "BTW this does not sound like a community issue, because the community is not responsible for downtime ATM."
> 
> 
> 
> > I'll disagree on that one - This isn't really about downtime IMO, its more about what it makes sense for us to invest/work on and it affects community if code.quarkus isn't readily available. If there are community members that can help on this thats great.
> 
> 
> 
> I mean that this is an uptime/reliability issue, and the service is provided by RH, not the community, ATM, and so we should be having the discussion about uptime and on-call duty and responsibility. This is a role that is typically compensated for, BTW, where people who are on call duty are not allowed to be away from keyboard further than X minutes and can't drink, in most cases I know of.
> 
> 
> 
> I think it's unfair to expect this service to fall on a single guy without it having been discussed (forgive me if it has), and it's unrealistic to think a single person can be on-call always without rotation.
> 
> 
> 
> So IMO this is the discussion we should be having: who's the on-call team, how do they synchronise, what's the procedure for emergency fixes, how do they get compensated for the extra constraints?
> 
> 
> 
> When you figure out how's that team, then you can ask them if they want to switch to Java.

Here we are first talking about code compiling and be able to fix the code in timely manner and not have it block quarkus release process - we really just need to fix or decouple these two. 

To be clear, I agree uptime and rollout is important and afaik we already have a team for that (SRE) - which rely on quarkus team as a whole to be able to fix issues if/when they occur. 

But I would think we aren't there yet where we should need a dedicated team to keep this running. If we do we should do what we can to avoid that imo.

**Comment by maxandersen** [comment]
> > "BTW, on that road, 80% of code.quarkus.io is frontend (typescript + react), who is going to fix bugs in it? Java would not change this"
> 
> > 
> 
> > 1. typescript + react rarely if ever requires custom setup to fix
> 
> > 2. these historically haven't had compile/build issues preventing an update
> 
> 
> 
> This is right, and make me think about a possible middle ground to make everyone happy. So as you said, the problem for releases would mostly be in the interface between the Quarkus platform and code.quarkus.io. We can have `.java` in a kotlin project, so let's rewrite that interface in java?
> 
> 
> 
> WDYT?

In my naive POV isn't that just about having tooling api In quarkus for the various Tasks code quarkus need to do (which is exactly same as what cli/build plugins need) ?

**Comment by ia3andy** [comment]
We will migrate only the interface code: https://github.com/quarkusio/code.quarkus.io/issues/400
