### ISSUE TITLE
Display transitive extensions

### ISSUE THREAD

**Issue by FroMage** [quarkusio/code.quarkus.io#38]
When you select an extension, it may depend on other extensions. It could be nice to display them in another colour.

This can wait until after the first release.

**Comment by FroMage** [comment]
Well I'd rather @ia3andy implemented this, Stale bot.

**Comment by ia3andy** [comment]
@aloubyansky do we have the info?

**Comment by aloubyansky** [comment]
Yes. E.g. look for "extension-dependencies" in https://repo1.maven.org/maven2/io/quarkus/quarkus-bom-quarkus-platform-descriptor/2.3.0.Final/quarkus-bom-quarkus-platform-descriptor-2.3.0.Final-2.3.0.Final.json

**Comment by FroMage** [comment]
Great!
