### ISSUE TITLE
Wrong dockerfile name in Dockerfile.fast-jar

### ISSUE THREAD

**Issue by survivant** [quarkusio/code.quarkus.io#381]
Quarkus code generated from the webpage produce 3 dockerfiles.  Quarkus 1.7.1.FINAL
 
but the file : Dockerfile.fast-jar

contains this line
docker build -f src/main/docker/Dockerfile.jvm -t quarkus/code-with-quarkus-jvm .

instead of
docker build -f src/main/docker/Dockerfile.fast-jar -t quarkus/code-with-quarkus-jvm .

**Comment by geoand** [comment]
I am pretty sure this was addressed by: https://github.com/quarkusio/quarkus/pull/11643

**Comment by ia3andy** [comment]
It will be on `1.8` then..
