### ISSUE TITLE
Push to Github fails

### ISSUE THREAD

**Issue by jeremyrdavis** [quarkusio/code.quarkus.io#382]
**Describe the bug**
"Push to Github" fails when generating a new project.  I tried with both the default selected REST functionality and with a few selected modules

**Expected behavior**
The project to prompt me for my Github credentials

**Actual behavior**
"Holy Supersonic Atoms! Fail to create the GitHub project"

Error message from the JavaScript console:
Access to fetch at 'https://api.github.com/repositories/288880252' (redirected from 'https://code.quarkus.io/api/github/project?g=org.acme&a=code-with-quarkus&v=1.0.0-SNAPSHOT&b=MAVEN&c=org.acme.ExampleResource&s=&cn=code.quarkus.io') from origin 'https://code.quarkus.io' has been blocked by CORS policy: Request header field github-state is not allowed by Access-Control-Allow-Headers in preflight response.

**To Reproduce**
1. Create a project using only the default selected, RESTEasy JAX-RS
2. Click Push to Github

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Browser:  
Chrome Version 84.0.4147.135 (Official Build) (64-bit)
Firefox Version 84.0.4147.135 (Official Build) (64-bit)
Safari Version 13.0.5 (14608.5.12)
 - OS: Mac OSX 10.14.6

**Comment by ia3andy** [comment]
Ah... this must be a side effect of `1.7.X`, I'll have a look tomorrow thanks!!

**Comment by ia3andy** [comment]
@jeremyrdavis I can't reproduce on Chrome, what browser did you use?

**Comment by jeremyrdavis** [comment]
I verified this morning using the same ones as well as Brave:
Chrome Version 84.0.4147.135 (Official Build) (64-bit)
Firefox Version 84.0.4147.135 (Official Build) (64-bit)
Safari Version 13.0.5 (14608.5.12)
Brave Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)

Firefox and Brave both take me to the Github login page while Chrome and Safari fail immediately

**Comment by ia3andy** [comment]
@jeremyrdavis if that's not too much too ask, could you open the developer console on chrome and send me the request/response headers which are failing.

**Comment by jeremyrdavis** [comment]
There is a 301 and a 204 that could be problemmatic

**301**
**Link:** 
https://code.quarkus.io/api/github/project?g=org.acme&a=code-with-quarkus&v=1.0.0-SNAPSHOT&b=MAVEN&c=org.acme.ExampleResource&s=&cn=code.quarkus.io

**Request headers:** 
POST /api/github/project?g=org.acme&a=code-with-quarkus&v=1.0.0-SNAPSHOT&b=MAVEN&c=org.acme.ExampleResource&s=&cn=code.quarkus.io HTTP/1.1
Host: code.quarkus.io
Connection: keep-alive
Content-Length: 0
DNT: 1
GitHub-State: 0.cywg040rzi
GitHub-Code: a0c665a4647045d546ae
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
Client-Name: code.quarkus.io
Accept: */*
Origin: https://code.quarkus.io
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://code.quarkus.io/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7
Cookie: AMCVS_945D02BE532957400A490D4C%40AdobeOrg=1; rh_omni_tc=701f2000001Css5AAC; sat_prevExtCmp=no%20value; scCidHist=701f2000001Css5AAC; s_cc=true; _ga=GA1.2.1455684667.1598289689; 2d9141e0d15db083d75f4cc993c92500=5462720a83c979fcf14b2f5165cc7fe6; _gid=GA1.2.1281161285.1598892791; dtm_prevProp=%7Ccode.quarkus.io; s_sq=%5B%5BB%5D%5D; AMCV_945D02BE532957400A490D4C%40AdobeOrg=-408604571%7CMCIDTS%7C18506%7CMCMID%7C65816543748320818203500870852828167462%7CMCAAMLH-1599502069%7C9%7CMCAAMB-1599502069%7C6G1ynYcLPuiQxYZrsz_pkqfLG9yMXBpb2zX5dvJdYQJzPXImdj0y%7CMCOPTOUT-1598904469s%7CNONE%7CMCSYNCSOP%7C411-18513%7CvVersion%7C4.6.0; dtm_prevURL=https%3A%2F%2Fquarkus.io%2Fguides%2Flogging; sat_ppv=100; _gat=1

**Response headers:**
HTTP/1.1 301 Moved Permanently
access-control-allow-origin: *
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
content-length: 150
content-security-policy: default-src 'none'
content-type: application/json;charset=utf-8
date: Wed, 02 Sep 2020 01:21:08 GMT
location: https://api.github.com/repositories/288880252
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
server: GitHub.com
status: 301 Moved Permanently
strict-transport-security: max-age=31536000; includeSubdomains; preload
vary: Accept-Encoding, Accept, X-Requested-With
x-accepted-oauth-scopes: admin:repo_hook, delete_repo, read:repo_hook, repo, repo:status, repo_deployment, security_events, write:repo_hook
x-content-type-options: nosniff
x-frame-options: deny
x-github-media-type: github.v3
x-github-request-id: B96B:3443:25639D5:4F0F12E:5F4EF384
x-oauth-client-id: 2145b086f8d27b53c4f5
x-oauth-scopes: public_repo
x-ratelimit-limit: 5000
x-ratelimit-remaining: 4998
x-ratelimit-reset: 1599013268
x-xss-protection: 1; mode=block

**204**
**Link**
https://api.github.com/repositories/288880252

**Request headers:**
OPTIONS /repositories/288880252 HTTP/1.1
Host: api.github.com
Connection: keep-alive
Accept: */*
Access-Control-Request-Method: GET
Access-Control-Request-Headers: client-name,github-code,github-state
Origin: https://code.quarkus.io
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Sec-Fetch-Dest: empty
Referer: https://code.quarkus.io/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7

**Response headers:**
HTTP/1.1 204 No Content
Server: GitHub.com
Date: Wed, 02 Sep 2020 01:21:08 GMT
Status: 204 No Content
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
Access-Control-Max-Age: 86400
Access-Control-Allow-Headers: Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Accept-Encoding, X-GitHub-OTP, X-Requested-With, User-Agent
Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Expect-CT: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com collector.githubapp.com avatars0.githubusercontent.com avatars1.githubusercontent.com avatars2.githubusercontent.com avatars3.githubusercontent.com github-cloud.s3.amazonaws.com; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/socket-worker.js gist.github.com/socket-worker.js
Vary: Accept-Encoding, Accept, X-Requested-With
X-GitHub-Request-Id: E106:2FA9:472E116:793683D:5F4EF384

**Comment by ia3andy** [comment]
this is really weird, the first request post to code.quarkus.io/api and `server: GitHub.com` answer the response. I will investigate..
