### ISSUE TITLE
code.quarkus.io not working on firefox

### ISSUE THREAD

**Issue by gabrielcunhazup** [quarkusio/code.quarkus.io#391]
I'm using Firefox 78.0.2, and I can not start a quarkus project accessing https://code.quarkus.io. I can only do that accessing https://stage.code.quarkus.io

**Expected behavior**
https://stage.code.quarkus.io and https://code.quarkus.io supposed to have the same behavior: give me the option to start a new quarkus project.

**Actual behavior**
When I actually access https://code.quarkus.io it only shows: `Start coding with code.quarkus.io`

**To Reproduce**
1. Access https://code.quarkus.io on firefox

**Screenshots**
![image](https://user-images.githubusercontent.com/64219483/93536068-a1604f00-f91e-11ea-8660-0005f94caf23.png)

**Environment (please complete the following information):**
 - Browser: Mozilla Firefox 78.0.2
 - OS: Ubuntu 19.10

**Comment by ia3andy** [comment]
@gabrielcunhazup could you send me the console logs?

**Comment by ia3andy** [comment]
@gabrielcunhazup try a shift+F5 also maybe?

**Comment by gabrielcunhazup** [comment]
Well, it worked :)
Thanks.
