### ISSUE TITLE
Frustrating info box

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#397]
**Description**
From feedback, the info box seems to be a problem in its current form:
- too big
- wrongly placed
- confusing for the user flow
- making it hard to see the search results appear

![image](https://user-images.githubusercontent.com/2223984/95201868-cdb21180-07e0-11eb-9220-0516533704e8.png)

**Comment by maxandersen** [comment]
I still get the big info box on first visit on desktop on stage.

**Comment by ia3andy** [comment]
@maxandersen yes it's still here, but the problem was that it was on the middle of the screen in the extension list. Now it's a clean popup on which you can select "never show again"..

**Comment by maxandersen** [comment]
Ok :)
