### ISSUE TITLE
Make the extensions.json consistant

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#40]
For now the file is generated from the common and the quarkusio ones. We need to find a more consistant way of achieving it.

**Comment by aloubyansky** [comment]
I think we need to generate it for every platform release. I guess, there could be a Maven plugin doing that.

**Comment by emmanuelbernard** [comment]
@aloubyansky that or this is our canonical way to define the platform. I.e. hosting the extension metadata and all

**Comment by aloubyansky** [comment]
The way it's looking now, it could easily be generated. The extension descriptor (which is generated by the bootstrap maven plugin) would have to be extended with the missing properties.
Then another maven plugin could take the platform BOM and generate the complete JSON file for it and attach it as an artifact to the platform maven project.

**Comment by ia3andy** [comment]
@aloubyansky could we create an issue in the repository containing that?

FYI, here are fields used:
```
    id: string;
    name: string;
    labels: string[];
    description?: string;
    shortName?: string;
    category: string;
```

We may need a new field `technical: boolean` to indicate the extension shouldn't be shown.

It would be great also to include the transitive deps as requested in this issue:
https://github.com/fabric8-launcher/launcher-quarkus/issues/38

**Comment by aloubyansky** [comment]
Sure. I'd like to have a bit of a discussion on the transitive deps though, basically to clarify the use-case for including them. Because the versions of the transitive deps could be managed differently depending on the context, e.g. different versions of the platform may include the same version of an extension but apply different DM.

**Comment by ia3andy** [comment]
@aloubyansky I guess we can wait for the transitive deps, I've been thinking a bit and it might not be easy to handle in the UI. Let's first have something consistant, we'll look at making it better in a second time. wdyt?

**Comment by aloubyansky** [comment]
Makes sense.

**Comment by maxandersen** [comment]
didn't know code.quarkus.io uses separate extensions.json.
We need to make sure things gets properly done for
related to https://github.com/quarkusio/quarkus/issues/4317

**Comment by gsmet** [comment]
@maxandersen code.quarkus.io aggregates the data from the main `extensions.json` with the data from the website (the ones from `_data/extensions.yaml`)

**Comment by maxandersen** [comment]
@gsmet could you add to https://github.com/quarkusio/quarkus/issues/4317 info on what that `_data/extensions.yaml` brings to the game - seem to just be additional categorization and overrides of labels ?

**Comment by emmanuelbernard** [comment]
I'm not sure _data/extensions.yaml is used much, it was used to generate https://quarkus.io/extensions/ but we want that to be deprecated in favor of code.quarkus.io. the extension page is no longer referenced from the website (or should not).
I do think code.quarkus.io uses and modify _data/extensions.yaml though and we would need to change that

**Comment by maxandersen** [comment]
Yes, that’s why if anyone know what from those files we *Actually* need that would help :)

**Comment by emmanuelbernard** [comment]
@gsmet is your man as he is release coordinator and has to manually update these today. He is traveling though.

**Comment by ia3andy** [comment]
Things are moving in the right direction :) 
- extension.json file is now auto-generated: https://github.com/quarkusio/quarkus/pull/4423
- it will soon contain all the data needed by Code Quarkus: https://github.com/quarkusio/quarkus/issues/4320

Once that's done, we will directly use the file provided by quarkus
