### ISSUE TITLE
Generated project test fails

### ISSUE THREAD

**Issue by fbricon** [quarkusio/code.quarkus.io#411]
[Project](https://github.com/fbricon/demo) generated by adding quarkus-amazon-lambda, quarkus-qute, quarkus-config-yaml, quarkus-resteasy fails to run tests:

> 
> [INFO] Running foo.bar.ExampleResourceTest
> Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.402 s <<< FAILURE! - in foo.bar.ExampleResourceTest
> Error:  testHelloEndpoint  Time elapsed: 0.006 s  <<< ERROR!
> java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
> Caused by: java.lang.RuntimeException: Failed to start quarkus
> Caused by: javax.enterprise.inject.spi.DeploymentException: No config value of type [java.lang.String] exists for: greeting.message

see https://github.com/fbricon/demo/runs/1429511562

**Comment by ia3andy** [comment]
@fbricon could you try without `quarkus-amazon-lambda`?

**Comment by fbricon** [comment]
Yeah test pass without lambda, fails with it. Nice catch.

**Comment by ia3andy** [comment]
@fbricon next release introduces a safety layer for some examples (like amazon-lambda) which don't behave well together :).

**Comment by ia3andy** [comment]
There is now an message explaining why it fails.
