### ISSUE TITLE
Search for extensions with codestarter

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/code.quarkus.io#420]
Introduce possibility to search for extensions with codestarters.

ATM I can type 'preview' in `Pick your extensions` search field and get the appropriate extensions.

There is no way to show just extensions with codestarter.

I can visually identify them when looking for fighter aircraft icon. But it's not `Ctrl+F` searchable.
There are many extensions and it is hard to spot the icons.

**Comment by rsvoboda** [comment]
To leverage current functionality, the fighter aircraft  icon could be replaced by text based label, e.g. 'codestarter'.

This label should be searchable by both Ctrl+F and "Pick your extensions" search.

**Comment by rsvoboda** [comment]
Looks like https://github.com/quarkusio/code.quarkus.io/blob/master/src/main/frontend/src/code-quarkus/pickers/extensions-picker.tsx#L55 is the place where switch to label instead of icon could be done

**Comment by gsmet** [comment]
I fail to see the need for that? You won't choose your dependencies depending of if a codestart is there or not? You will choose them depending on what you need.

**Comment by rsvoboda** [comment]
End user use-case - improves getting started experience for newcomers who are just looking around, not decided on the set of extension they need.

My use-case - to easily find extensions with codestarters for testing analysis.

I can get the info from https://code.quarkus.io/api/extensions but that's not for everybody.

**Comment by rsvoboda** [comment]
This is the command line way to get the list of extensions with code example:`curl https://code.quarkus.io/api/extensions 2>/dev/null | jq '.[] | select(.tags[] | contains("provides-example")) | .id' | sort | uniq`

@ia3andy hinted that I can use `provides` or `provides-example` in the search bar too.

**Comment by ia3andy** [comment]
This is going to be part of: https://github.com/quarkusio/code.quarkus.io/issues/459

**Comment by ia3andy** [comment]
Closing as it's a duplicate
