### ISSUE TITLE
Discuss deprecating extension shortId

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#424]
Currently in code.quarkus.io the shortId is available in the api:
- https://code.quarkus.io/api/extensions
- and https://code.quarkus.io/api/download (`s` param)
 
They are used by the frontend in the share feature and during the github flow to have shorter urls, ex:
- https://code.quarkus.io/d?g=org.acme&a=code-with-quarkus&v=1.0.0-SNAPSHOT&b=MAVEN&s=49J.YjV.8iY.F9R.CPa&cn=code.quarkus.io
- https://code.quarkus.io/?g=org.acme&a=code-with-quarkus&v=1.0.0-SNAPSHOT&b=MAVEN&s=49J.YjV.8iY.F9R.CPa&cn=code.quarkus.io

Here we are discussing deprecating the `shortId` because it will be a problem for the multi platforms support in code.quarkus.io.

We are trying to gather if it is used anywhere else...

And we may also discuss possible alternatives..

**Comment by ia3andy** [comment]
After discussing on zulip, the current preferred alternative it to use a deterministic compression algo using shortcuts, that could be implemented client side:
```
io.quarkus:quarkus-resteasy -> resteasy@q
io.quarkiverse.myext:quarkus-my-ext -> my-ext@qv
```

We would:
- remove the shortIds from the extension endpoint and the `s` in the download one
- we could add new supported shortcuts later in the future
- full GA would also still work `io.quarkus:quarkus-resteasy`

Benefits are that it would cover most of the use cases without too much coupling.

**Comment by ia3andy** [comment]
cc @maxandersen @jeffmaury @xorye @azerr @fbricon

**Comment by jeffmaury** [comment]
Quarkus Tools for Eclipse and IntelliJ are using shortIds

**Comment by ia3andy** [comment]
Ok @jeffmaury that's good to know. No worries, we will keep support for it a while and provide instruction on the good way forward ;-)

**Comment by ia3andy** [comment]
@jeffmaury do you show the download url to the user at some point?

**Comment by jeffmaury** [comment]
No the API is used internally through wizard. The only URL that is exposed to the user is the root endpoint (https://code.quarkus.io by default) that user is allowed to change to use its own deployment or the Red Hat one

**Comment by ia3andy** [comment]
Ok, @jeffmaury to prepare a great future, what do you think about having a POST endpoint to get the zip download url?

The first implementation will break if there are too much selected extensions, but in the future we may improve it if we hit too much error (without any change in the IDEs)..

**Comment by jeffmaury** [comment]
TBH, I always thought that was the right solution 😍 
So +1 to go that path

**Comment by ia3andy** [comment]
@jeffmaury did you tell it to me?

**Comment by jeffmaury** [comment]
No, my bad, I had the feeling GET was required as it was exposed in various docs, blogs,...

**Comment by ia3andy** [comment]
@jeffmaury the GET will still work, the POST will return nearly the same GET with a few optimization.

**Comment by ia3andy** [comment]
Ok, the new api is now available on staging ready to be implemented:
```bash
$ curl -H "Content-Type: application/json" -X POST https://stage.code.quarkus.io/api/download --output test-empty-post.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20562    0 20562    0     0  30105      0 --:--:-- --:--:-- --:--:-- 30061

$ curl -H "Content-Type: application/json" --data '{"groupId":"new.api","artifactId":"new-api","extensions":["io.quarkus:quarkus-resteasy-qute","io.quarkus:quarkus-hibernate-validator"],"buildTool":"GRADLE_KOTLIN_DSL"}' -X POST https://stage.code.quarkus.io/api/download --output test-post.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 69534    0 69367  100   167  80847    194 --:--:-- --:--:-- --:--:-- 80947

$ unzip -l test-post.zip
Archive:  test-post.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  02-21-2021 09:28   new-api/
        0  02-21-2021 09:28   new-api/src/
        0  02-21-2021 09:28   new-api/src/main/
        0  02-21-2021 09:28   new-api/src/main/java/
        0  02-21-2021 09:28   new-api/src/main/java/new/
        0  02-21-2021 09:28   new-api/src/main/java/new/api/
        0  02-21-2021 09:28   new-api/src/main/java/new/api/qute/
     1416  02-21-2021 09:28   new-api/src/main/java/new/api/qute/QuteResource.java
      492  02-21-2021 09:28   new-api/src/main/java/new/api/qute/Quark.java
        0  02-21-2021 09:28   new-api/src/main/resources/
        0  02-21-2021 09:28   new-api/src/main/resources/templates/
     1373  02-21-2021 09:28   new-api/src/main/resources/templates/page.qute.html
        0  02-21-2021 09:28   new-api/src/main/resources/application.properties
        0  02-21-2021 09:28   new-api/src/main/resources/META-INF/
        0  02-21-2021 09:28   new-api/src/main/resources/META-INF/resources/
     6283  02-21-2021 09:28   new-api/src/main/resources/META-INF/resources/index.html
        0  02-21-2021 09:28   new-api/src/main/docker/
     2161  02-21-2021 09:28   new-api/src/main/docker/Dockerfile.fast-jar
     1847  02-21-2021 09:28   new-api/src/main/docker/Dockerfile.jvm
      695  02-21-2021 09:28   new-api/src/main/docker/Dockerfile.native
        0  02-21-2021 09:28   new-api/gradle/
        0  02-21-2021 09:28   new-api/gradle/wrapper/
    58910  02-21-2021 09:28   new-api/gradle/wrapper/gradle-wrapper.jar
      202  02-21-2021 09:28   new-api/gradle/wrapper/gradle-wrapper.properties
      196  02-21-2021 09:28   new-api/gradle.properties
      268  02-21-2021 09:28   new-api/.gitignore
      316  02-21-2021 09:28   new-api/settings.gradle.kts
      852  02-21-2021 09:28   new-api/build.gradle.kts
     1669  02-21-2021 09:28   new-api/README.md
       71  02-21-2021 09:28   new-api/.dockerignore
     5770  02-21-2021 09:28   new-api/gradlew
     3058  02-21-2021 09:28   new-api/gradlew.bat
---------                     -------
    85579                     32 files
```


and the `/api/project`:
```bash
$ curl -H "Content-Type: application/json" --data '{"groupId":"new.api","artifactId":"new-api","extensions":["io.quarkus:quarkus-resteasy-qute","io.quarkus:quarkus-hibernate-validator"],"buildTool":"GRADLE_KOTLIN_DSL"}' -X POST https://stage.code.quarkus.io/api/project            
{"path":"/d?g=new.api&a=new-api&b=GRADLE_KOTLIN_DSL&e=io.quarkus%3Aquarkus-hibernate-validator&e=io.quarkus%3Aquarkus-resteasy-qute"}
```


It will be available soon on https://code.quarkus.stage.redhat.com/ and in production later today after a few tests.

**Comment by ia3andy** [comment]
@jeffmaury @xorye @azerr @fbricon Now that this is implemented everywhere, could you make sure IDE plugins are up to date using `POST /api/download`. 

We will be forced to remove support for `shortId`s quite soon..

**Comment by ia3andy** [comment]
@jeffmaury has implemented this for IntelliJ and JBoss Tools. What's the status of the other plugins?

Closing this issue as it's fixed on code.quarkus.io

**Comment by ia3andy** [comment]
@jeffmaury @xorye @azerr @fbricon  I still get warning of shortIds being used (without any client information). Do you have an idea what could be the source?

In the near future, I will remove support for it (it will not fail but won't select any extension)

**Comment by jeffmaury** [comment]
Quarkus Tools for Eclipse/IntelliJ don't use short ids since they moved to POST

**Comment by ia3andy** [comment]
Thanks @jeffmaury I will check vscode..

The PR to drop support is ready: https://github.com/quarkusio/code.quarkus.io/pull/680

(Only the `s=...` will be ignored)

**Comment by fbricon** [comment]
`s=` usage might be from Jetbrains's own Quarkus support

**Comment by ia3andy** [comment]
@fbricon do you know if this code is open source?

**Comment by fbricon** [comment]
I don't think so, it's part of IDEA Ultimate

**Comment by ia3andy** [comment]
@maxandersen any idea on how we could reach them?

**Comment by jeffmaury** [comment]
They have a Slack channel (https://jetbrains.slack.com/archives/GQQ382C9F) but I don't know if it's open to everyone but at least Max and I are there
