### ISSUE TITLE
When selecting a jackson extension and kotlin jackson-kotlin-module should be added to the dependencies

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/code.quarkus.io#426]
**Description**
When a user selects a jackson extension (e.g. RESTEasy Jackson) and the Kotlin language, the dependency `com.fasterxml.jackson.module:jackson-module-kotlin` should be added automatically.

**Comment by maxandersen** [comment]
This is still an issue Afaics but it isn't really a issue for code quarkus but more in core. 

@aloubyansky did we have the mechanisms in place yet to register these helper extensions ?

**Comment by aloubyansky** [comment]
Conditional dependencies? Yes, it's officially in now.

**Comment by andreas-eberle** [comment]
@maxandersen : Core says won't fix ;) https://github.com/quarkusio/quarkus/issues/18409#issuecomment-874532858

**Comment by andreas-eberle** [comment]
The Core issue https://github.com/quarkusio/quarkus/issues/18409#issuecomment-874532858 has been reopened and makes this one obsolete.
