### ISSUE TITLE
Example should not fallback to `resteasy` when a `resteasy-reactive-*` extension is selected

### ISSUE THREAD

**Issue by BrainShit** [quarkusio/code.quarkus.io#435]
**Describe the bug**
When you create a new application using code.quarkus.com and choose resteasy-reactive-jsonb or resteasy-reactive-jackson or resteasy-reactive-qute the pom.xml/build.gradle still includes resteasy classic.
When you include reasteasy-reactive in combination resteasy classic is not included.

**Expected behavior**
Not including resteasy classic

**Actual behavior**
Includes resteasy classic

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1.  go to code.quarkus.com
2.  only include one of the mentioned resteasy-reactive classes
3.  download or push to github and check the pom.xml/build.gradle

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Browser: chromium 87
 - OS: windows 10

**Additional context**
(Add any other context about the problem here.)

**Comment by ia3andy** [comment]
Hey @BrainShit I can't reproduce this, when generating this app: https://code.quarkus.io/?a=reactive-app&s=WJu.sTz.tEq.X8W&extension-search=resteasy%20reactive I get this in the pom which seems ok:
```xml
<dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jsonb</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-qute</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

```

**Comment by BrainShit** [comment]
If you do not choose the resteasy-reactive extension yourself, as it is inferred (I hope that's the right word) when you choose any of the extensions building ontop of it the classic version gets added. Similar to when you directly choose the resteasy classic jacksion extension.

Try this:
https://code.quarkus.io/?a=reactive-app&s=sTz.tEq.X8W&extension-search=resteasy%20reactive

**Comment by ia3andy** [comment]
Ah ok, gotcha :)

Yeah this is indeed a tricky bug.. Good catch!

It's due to the fact that `resteasy` is the "fallback" example when there is no other selected example. I am not sure how we should fix it :-/

CC @maxandersen

**Comment by maxandersen** [comment]
Is the fix to have a QuickStart for resteasy-reactive ?

**Comment by ia3andy** [comment]
Yeah it's fixed we can close
