### ISSUE TITLE
Return HTTP 400 instead of 500 when making erroneous extension selection

### ISSUE THREAD

**Issue by geoand** [quarkusio/code.quarkus.io#436]
Originally reported at: https://youtrack.jetbrains.com/issue/IDEA-255635

A "client" that makes an erroneous selection of extensions should get the proper HTTP response (400) indicating that something is wrong with the input data

**Comment by ia3andy** [comment]
Ok here is a reproducer: https://code.quarkus.io/d?s=Pqi.K2H.oru.yZc&cn=code.quarkus.io I will catch it and throw a 400

**Comment by geoand** [comment]
Thanks
