### ISSUE TITLE
Have an obvious way of finding how to add new extensions

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#44]
@emmanuelbernard I think we are missing that

**Comment by emmanuelbernard** [comment]
I don't understand.

**Comment by emmanuelbernard** [comment]
BTW do you mind adding me as a member to the fabric8-launcher, It seems necessary to be able to change the email  address github sends you notifications to.

**Comment by ia3andy** [comment]
> do you mind adding me as a member to the fabric8-launcher
@emmanuelbernard I just added you..

> I don't understand.

I mean when you see the list of extensions, you may ask yourself:
- Why is that extension missing?
- How can I add/integrate a missing extension to the list

**Comment by emmanuelbernard** [comment]
I still don't understand. In which context is the person asking that question.

**Comment by ia3andy** [comment]
@emmanuelbernard on code.quarkus.io, you can pick extensions, copy add extension commands, generate application but there is not place where you can find info on how to contribute extensions. 

Example, I want to connect to a Cassandra DB, I type `cassandra` in the search box:
![image](https://user-images.githubusercontent.com/2223984/62541857-ecbeb780-b85a-11e9-9503-845f57566c85.png)

So I was thinking about adding a text like: "We don't have any extension for 'cassandra' yet, follow [this guide] to provide a new extension in the Quarkus ecosystem".

And something at the bottom of the full list. "You can't find the extension you are looking for? Follow [this guide] to provide a new extension in the Quarkus ecosystem
