### ISSUE TITLE
Add "Open in IDEA button" in the "after push to GitHub" modal

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#445]
**Description**
It seems there is a library to check if a protocol is supported:
https://www.npmjs.com/package/custom-protocol-check

Also here is how the Jetbrains Toolbox opens it:
https://github.com/JetBrains/toolbox-browser-extension/blob/master/api/toolbox.js#L4

**Comment by RubensKj** [comment]
That's a pretty awesome feature!! 🎉

I will look about it in the next few days

**Comment by RubensKj** [comment]
I added a modal in order to show the user a result of the click of button, if you don't like I can remove.

If you like it, another thing that would be cool is add a debounced function where the `IdeaModal` will close after a time, like 5 seconds.. wdyt??

**Comment by Joy1654** [comment]
Add "Open in IDEA button" in the "after push to GitHub" modal #445,.....
Hi there, I am really new in this , Can you explain me what is exactly I have to do here...

**Comment by ia3andy** [comment]
Sorry @Joy1654 we are going to close this issue.

@RubensKj tried but we can't detect if the plugin is installed without showing a notification in the browser to everyone (which is not acceptable).
