### ISSUE TITLE
Push to Github uses master branch should be main

### ISSUE THREAD

**Issue by jeffmaury** [quarkusio/code.quarkus.io#447]
**Description**
(Describe the feature here.)
When the application code is pushed to GitHub, the default branch is master, should be main

**Comment by maxandersen** [comment]
It should be whatever is the default as the org could have Different defaults.

**Comment by jeffmaury** [comment]
Checked and my account is configured with default branch = main

**Comment by maxandersen** [comment]
Yes and that's what the fix should be. Use the default name rather than assume its main.

**Comment by ia3andy** [comment]
Well, it's no easy because it uses the default branch from the server :-p and the target repo doesn't exist. So it's either one or the other, I would go for `main` no?

**Comment by ia3andy** [comment]
We either need to call the api to get the user default branch, but I didn't find the right call to get it or maybe jgit is using an hardcoded branch?

@gastaldi any thoughts?

**Comment by gastaldi** [comment]
Before we dig further, if code.quarkus.io creates the repository, maybe it could always use `main` and assume that everytime?

**Comment by maxandersen** [comment]
Can't you just push to HEAD ? That will push to the default branch.

**Comment by ia3andy** [comment]
this is fixed on the "next" branch and will be online with 2.0

**Comment by ia3andy** [comment]
Ok it's a bit more complex than I thought, it was working locally because my git config is set up with "main", but the server is setup with "master". We need to fetch that from the github api which makes it quite complex. Maybe we could default to "main"?

**Comment by ia3andy** [comment]
Closed by https://github.com/quarkusio/code.quarkus.io/pull/498

**Comment by ia3andy** [comment]
I just tested and it works on staging :)

It will soon be in prod!!
