### ISSUE TITLE
Extension "cart" button with extensions

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#457]
**Description**
Add a new small button at the left of the "Generate your application" button.

- This button contains a counter of selected extensions and an icon to represent extensions TBD
- On mouse over, like one the "Generate your application" button, it shows the list of selected extensions in a dropdown with the ability to delete them.
- The list of extensions can now take the full width
- The search bar goes at the top of it (and will soon be improved)

**Comment by RubensKj** [comment]
Hey @ia3andy, I'll have a closer look in the next few weeks

I have some doubt about this feature. This should be like the `Pick your extensions` & `Selected Extensions` we have in the left menu??

**Comment by ia3andy** [comment]
Yeah this is to replace the actual "left panel" which currently contain the search bar + selected extensions.

I would optimise the space for extensions.

**Comment by ia3andy** [comment]
Having more space for the search bar will allow: https://github.com/quarkusio/code.quarkus.io/issues/459

**Comment by ia3andy** [comment]
@RubensKj fyi I started this one, let me know, when you are ready and I'll find you something..

**Comment by RubensKj** [comment]
Oh ok!! I still very busy with work and university..
