### ISSUE TITLE
No matter what, Quarkus does not create an executable jar

### ISSUE THREAD

**Issue by mhash17** [quarkusio/code.quarkus.io#464]
**Describe the bug**
I've tried to generate a quarkus application. when i package it with mvn package it does not create a runnable jar; but everywhere it is stated that there will be two jars created (one of them as the -runner.jar). But that is not the case here. I've tried it with different approaches like VS Code quarkus plugin; maven command and also by downloading a zip from code.quarkus.io. I've also checked if the quarkus-maven-plugin is defined at pom.xml. It never creates a runnable jar. 

**Expected behavior**
create a runnable jar under target directory.

**Actual behavior**
no runnable jar under target directory.

**To Reproduce**
1. go to code.quarkus.io and generate simple application
2.  unzip the folder and cd into it
3.  run mvn clean package
4. check target directory

**Environment:**
 - Browser: chrome
 - OS: windows 10

**Additional context**
OpenJDK 11; GraalVM CE 21.1.0

**Comment by mhash17** [comment]
maybe it's in the wrong repo? could you please move/delete it, sorry 🤦🏽

**Comment by maxandersen** [comment]
You need to run mvn package to get the jars.  

Mvn clean just cleans.

**Comment by mhash17** [comment]
> You need to run mvn package to get the jars.
> 
> Mvn clean just cleans.

mvn clean package -> mvn clean & mvn package 
Btw: a simple jar is created but not a runnable jar. That's the problem here.

**Comment by ia3andy** [comment]
@mhash17  since we use the `fast-jar` as default, you can run it using:
```shell
java -jar target/quarkus-app/quarkus-run.jar
```

You can always change the packaging type.

**Comment by mhash17** [comment]
Ok thank you, now i see that by v.1.13 it changed the location. Shouldn't someone edit the tutorial to meet this fact (if it is still relevant)?
https://quarkus.io/quarkus-workshops/super-heroes/#_packaging_and_running_the_application

**Comment by maxandersen** [comment]
Open issue on the tutorial will be best. 

Cc @cescoffier @emmanuelbernard who worked on the tutorial

**Comment by cescoffier** [comment]
Yes, please open an issue on the workshop directly. The workshop has been written for a much older version of Quarkus. Several parts (including this one) need to be rewritten.
