### ISSUE TITLE
Fails in generating gradle project with Azure Function

### ISSUE THREAD

**Issue by Tomasz-Trzcinski-Spyro** [quarkusio/code.quarkus.io#470]
**Describe the bug**
I tried to generate new project in
https://code.quarkus.io/?g=org.ttrzcinski&a=quarkus-az-func&b=GRADLE&e=resteasy&e=rest-client&e=azure-functions-http&extension-search=azure%20f

with:
![image](https://user-images.githubusercontent.com/84383748/119138550-49945d80-ba42-11eb-9ed0-6c1b18c1ea91.png)
artifact: quarkus-az-func
build tool: gradle

RESTEasy JAX-RS
REST Client
Azure Function HTTP

**Expected behavior**
Generated ZIP archive with project inside.

**Actual behavior**
Redirect to message:
Internal Server Error
io.quarkus.devtools.codestarts.CodestartStructureException: something is wrong, smart-pom-merge file strategy must only be used on maven projectsError id 579cb543-4c06-4e31-b396-93061d04811a-3

**To Reproduce**
1. Go to https://code.quarkus.io/
2. Change group and artifact to custom value
3. Change build tool to gradle
4. Find and add to project:
  - Rest Client
  - RESTEasy JAX-RS
  - Azure Function HTTP

**Screenshots**
Attached above.

**Environment (please complete the following information):**
 - Browser: Firefox 88.0.1 (64-bit)
 - OS: Windows 10

**Additional context**
---

**Comment by ia3andy** [comment]
Hey @Tomasz-Trzcinski-Spyro yeah this is a known issue, the Azure Function HTTP example is not compatible with Gradle. You could just disable example code to make it generate, but I am not sure it is possible to use it with Gradle. 

At some point we will improve that error, thanks for reporting it ;)

CC @maxandersen

**Comment by Tomasz-Trzcinski-Spyro** [comment]
OK, will do that.
