### ISSUE TITLE
Search for "CODE" label doesn't work

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/code.quarkus.io#484]
Search for "CODE" label doesn't work, don't see extensions with code examples.

I can search for "EXPERIMENTRAL" / "PREVIEW", but not for "CODE".

![Screenshot 2021-07-08 at 9 19 27](https://user-images.githubusercontent.com/925259/124879617-b3a29b00-dfcd-11eb-9f17-b06f22299845.png)

**Comment by ia3andy** [comment]
Thanks @rsvoboda it's on my task list :)

for now, the tag is still `provides-code` behind the scene but it wasn't nice in the UI. It will be `code` very soon.

Also I will pretty soon start to work on the [search bar](https://github.com/quarkusio/code.quarkus.io/issues/459) to make it easier to use those kind of filters..

**Comment by ia3andy** [comment]
@rsvoboda https://stage.code.quarkus.io/?extension-search=code

ok for prod?

**Comment by rsvoboda** [comment]
Nice, thanks @ia3andy
