### ISSUE TITLE
Adding the equivalent `enforcedPlatform` bom for Gradle projects

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#500]
BTW, we haven't considered adding the equivalent `enforcedPlatform` for Gradle projects, have we?

_Originally posted by @aloubyansky in https://github.com/quarkusio/code.quarkus.io/issues/499#issuecomment-886586847_

**Comment by ia3andy** [comment]
> BTW, we haven't considered adding the equivalent `enforcedPlatform` for Gradle projects, have we?

If we do add it, then we also need the dependency snippet for Gradle and to avoid having too many things, I would make it contextual to the selected build tool..

**Comment by aloubyansky** [comment]
Makes sense.

**Comment by ia3andy** [comment]
I think this menu is already too big, still, the drawback of making it contextual, is that people might not find that feature but I guess it's better than being incomplete. 

@phillip-kruger any thoughts?

**Comment by phillip-kruger** [comment]
How about only show maven or gradle based on :
![image](https://user-images.githubusercontent.com/6836179/126994921-10304bf6-86e1-4f34-a673-ddb4824576fc.png)

**Comment by phillip-kruger** [comment]
And probably add browser storage to remember the choice (maven / gradle) so if I come back my preference is selected

**Comment by ia3andy** [comment]
> How about only show maven or gradle based on :
> ![image](https://user-images.githubusercontent.com/6836179/126994921-10304bf6-86e1-4f34-a673-ddb4824576fc.png)

That what I meant by contextual

> And probably add browser storage to remember the choice (maven / gradle) so if I come back my preference is selected

That's a good idea..

**Comment by ia3andy** [comment]
@phillip-kruger and this one :)

**Comment by ia3andy** [comment]
duplicate of #555
