### ISSUE TITLE
Build tool documentation incomplete

### ISSUE THREAD

**Issue by jeffmaury** [quarkusio/code.quarkus.io#512]
**Describe the bug**
The OpenAPI documentation does not detail all the possible values for the build tool parameter (Gradle Kotlin is missing)

**Expected behavior**
Gradle Kotlin documented

**Actual behavior**
Only Maven and Gradle (Grrovy) are documented

**To Reproduce**
1. See https://code.quarkus.io/q/swagger-ui/#/Download/post_api_download 

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Browser: 
 - OS: 

**Additional context**
(Add any other context about the problem here.)

**Comment by phillip-kruger** [comment]
Hi @jeffmaury 

I updated the field description to include gradle_kotlin and I also made the schema a enum (as only those three values are valid)

See:

![image](https://user-images.githubusercontent.com/6836179/129152134-052bd9bc-3414-4f4f-a26a-66e4678aca8c.png)

is this fixing your issue ?

**Comment by jeffmaury** [comment]
Yes but I also noted that this information (as well as other parameters metadata) is absent from the schema for the POST method, can you fix it or do you want me to open another issue ?

**Comment by phillip-kruger** [comment]
I'll have a look at the post, seems like there we accept a json file, let me see what I can do

**Comment by phillip-kruger** [comment]
@jeffmaury I added the description on the POST Object as well:
![image](https://user-images.githubusercontent.com/6836179/129192850-a27671e6-634d-4b51-9a3c-84f0b0a5742e.png)

I am preparing a new PR for that. Hope that solves your issue

**Comment by jeffmaury** [comment]
Better but you should compare the doc for the get and the doc for the post: some metadatas are missing (default value,....)

**Comment by phillip-kruger** [comment]
I am not sure that all the default values apply on POST ? @ia3andy ? We can have some default values in parameters, but for sending the json ?

**Comment by ia3andy** [comment]
@phillip-kruger we need to make sure, but afaic it should be the same for POST

**Comment by phillip-kruger** [comment]
@jeffmaury ok I think I have everything now
![image](https://user-images.githubusercontent.com/6836179/129203188-dbadb59e-ab54-4863-8e89-75433c0adbbf.png)
