### ISSUE TITLE
stage.code.quarkus.io returning 500 in a very specific case

### ISSUE THREAD

**Issue by jeffmaury** [quarkusio/code.quarkus.io#525]
**Describe the bug**

Quarkus Tools for IntelliJ has an it test that selects all the extensions. It is now failing with 500 status code.

**Expected behavior**

200 should be returned

**Actual behavior**

500 status code is returned.

**To Reproduce**
1. Clone redhat-developer/intellij-quarkus
2. run `./gradlew test --tests com.redhat.devtools.intellij.quarkus.module.QuarkusModelRegistryTest`

**Screenshots**

![image](https://user-images.githubusercontent.com/695993/130261822-5fadf06e-1c62-4ac8-8428-62c7a2f2dbc2.png)

**Additional context**

Previous jobs that were ok before: https://github.com/redhat-developer/intellij-quarkus/actions/workflows/ci.yml

**Comment by phillip-kruger** [comment]
http://localhost:8080/api/download?e=resteasy&e=resteasy-jackson&e=resteasy-jsonb&e=vertx-graphql&e=grpc&e=hibernate-validator&e=jaxrs-client-reactive&e=rest-client-mutiny&e=reactive-messaging-http&e=vertx-web&e=rest-client&e=rest-client-jackson&e=rest-client-jaxb&e=rest-client-jsonb&e=rest-client-reactive&e=rest-client-reactive-jackson&e=hibernate-orm-rest-data-panache&e=resteasy-jaxb&e=resteasy-multipart&e=resteasy-mutiny&e=resteasy-qute&e=resteasy-reactive&e=resteasy-reactive-jackson&e=resteasy-reactive-jsonb&e=resteasy-reactive-links&e=resteasy-reactive-qute&e=smallrye-graphql&e=smallrye-graphql-client&e=smallrye-jwt&e=smallrye-openapi&e=undertow&e=webjars-locator&e=websockets&e=websockets-client&e=hibernate-orm&e=hibernate-orm-panache&e=jdbc-postgresql&e=jdbc-mariadb&e=jdbc-mysql&e=jdbc-h2&e=jdbc-mssql&e=jdbc-db2&e=jdbc-derby&e=jdbc-oracle&e=agroal&e=amazon-dynamodb&e=amazon-iam&e=amazon-kms&e=amazon-s3&e=amazon-ses&e=amazon-sns&e=amazon-sqs&e=amazon-ssm&e=com.blazebit%3Ablaze-persistence-integration-quarkus&e=cache&e=elasticsearch-rest-high-level-client&e=elasticsearch-rest-client&e=com.datastax.oss.quarkus%3Acassandra-quarkus-client&e=flyway&e=io.quarkiverse.googlecloudservices%3Aquarkus-google-cloud-bigquery&e=io.quarkiverse.googlecloudservices%3Aquarkus-google-cloud-bigtable&e=io.quarkiverse.googlecloudservices%3Aquarkus-google-cloud-firestore&e=io.quarkiverse.googlecloudservices%3Aquarkus-google-cloud-spanner&e=com.hazelcast%3Aquarkus-hazelcast-client&e=hibernate-envers&e=hibernate-orm-panache-kotlin&e=hibernate-reactive&e=hibernate-reactive-panache&e=hibernate-search-orm-elasticsearch&e=hibernate-search-orm-elasticsearch-aws&e=infinispan-client&e=liquibase&e=mongodb-client&e=mongodb-panache&e=mongodb-panache-kotlin&e=narayana-jta&e=narayana-stm&e=neo4j&e=reactive-db2-client&e=reactive-mssql-client&e=reactive-pg-client&e=reactive-mysql-client&e=redis-client&e=mongodb-rest-data-panache&e=smallrye-reactive-messaging&e=smallrye-reactive-messaging-amqp&e=smallrye-reactive-messaging-kafka&e=smallrye-reactive-messaging-mqtt&e=org.amqphub.quarkus%3Aquarkus-qpid-jms&e=kafka-client&e=kafka-streams&e=artemis-jms&e=io.quarkiverse.googlecloudservices%3Aquarkus-google-cloud-pubsub&e=config-yaml&e=logging-json&e=consul-config&e=logging-gelf&e=logging-sentry&e=vertx&e=mutiny&e=smallrye-context-propagation&e=kubernetes&e=openshift&e=smallrye-health&e=smallrye-fault-tolerance&e=amazon-alexa&e=amazon-lambda&e=amazon-lambda-rest&e=amazon-lambda-http&e=amazon-lambda-xray&e=azure-functions-http&e=container-image-docker&e=container-image-jib&e=container-image-openshift&e=container-image-s2i&e=funqy-amazon-lambda&e=funqy-google-cloud-functions&e=funqy-http&e=funqy-knative-events&e=google-cloud-functions&e=google-cloud-functions-http&e=io.quarkiverse.googlecloudservices%3Aquarkus-google-cloud-secret-manager&e=io.quarkiverse.googlecloudservices%3Aquarkus-google-cloud-storage&e=kubernetes-client&e=kubernetes-config&e=kubernetes-service-binding&e=minikube&e=openshift-client&e=micrometer&e=micrometer-registry-prometheus&e=opentelemetry&e=opentelemetry-exporter-jaeger&e=opentelemetry-exporter-otlp&e=smallrye-metrics&e=smallrye-opentracing&e=oidc&e=elytron-security-jdbc&e=elytron-security-ldap&e=elytron-security-oauth2&e=elytron-security-properties-file&e=keycloak-admin-client&e=keycloak-authorization&e=oidc-client&e=oidc-client-filter&e=oidc-client-reactive-filter&e=oidc-token-propagation&e=security-jpa&e=smallrye-jwt-build&e=vault&e=avro&e=apicurio-registry-avro&e=jackson&e=jaxb&e=jsonb&e=jsonp&e=org.optaplanner%3Aoptaplanner-quarkus-jackson&e=org.optaplanner%3Aoptaplanner-quarkus-jsonb&e=tika&e=jacoco&e=jgit&e=mailer&e=picocli&e=quartz&e=qute&e=scheduler&e=spring-boot-properties&e=spring-cache&e=spring-cloud-config-client&e=spring-data-jpa&e=spring-data-rest&e=spring-di&e=spring-scheduled&e=spring-security&e=spring-web&e=kotlin&e=scala&e=org.apache.camel.quarkus%3Acamel-quarkus-core&e=org.apache.camel.quarkus%3Acamel-quarkus-activemq&e=org.apache.camel.quarkus%3Acamel-quarkus-amqp&e=org.apache.camel.quarkus%3Acamel-quarkus-arangodb&e=org.apache.camel.quarkus%3Acamel-quarkus-as2&e=org.apache.camel.quarkus%3Acamel-quarkus-ahc&e=org.apache.camel.quarkus%3Acamel-quarkus-ahc-ws&e=org.apache.camel.quarkus%3Acamel-quarkus-atlasmap&e=org.apache.camel.quarkus%3Acamel-quarkus-atom&e=org.apache.camel.quarkus%3Acamel-quarkus-avro&e=org.apache.camel.quarkus%3Acamel-quarkus-attachments&e=org.apache.camel.quarkus%3Acamel-quarkus-jackson-avro&e=org.apache.camel.quarkus%3Acamel-quarkus-avro-rpc&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-athena&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-cw&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-ddb&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-ec2&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-ecs&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-eks&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-eventbridge&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-iam&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-kms&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-kinesis&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-lambda&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-msk&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-mq&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-s3&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-sts&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-ses&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-sns&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-sqs&e=org.apache.camel.quarkus%3Acamel-quarkus-aws2-translate&e=org.apache.camel.quarkus%3Acamel-quarkus-azure-eventhubs&e=org.apache.camel.quarkus%3Acamel-quarkus-azure-storage-blob&e=org.apache.camel.quarkus%3Acamel-quarkus-azure-storage-queue&e=org.apache.camel.quarkus%3Acamel-quarkus-base64&e=org.apache.camel.quarkus%3Acamel-quarkus-bean&e=org.apache.camel.quarkus%3Acamel-quarkus-bean-validator&e=org.apache.camel.quarkus%3Acamel-quarkus-bindy&e=org.apache.camel.quarkus%3Acamel-quarkus-box&e=org.apache.camel.quarkus%3Acamel-quarkus-braintree&e=org.apache.camel.quarkus%3Acamel-quarkus-browse&e=org.apache.camel.quarkus%3Acamel-quarkus-caffeine&e=org.apache.camel.quarkus%3Acamel-quarkus-caffeine-lrucache&e=org.apache.camel.quarkus%3Acamel-quarkus-cassandraql&e=org.apache.camel.quarkus%3Acamel-quarkus-cbor&e=org.apache.camel.quarkus%3Acamel-quarkus-consul&e=org.apache.camel.quarkus%3Acamel-quarkus-controlbus&e=org.apache.camel.quarkus%3Acamel-quarkus-couchdb&e=org.apache.camel.quarkus%3Acamel-quarkus-cron&e=org.apache.camel.quarkus%3Acamel-quarkus-crypto&e=org.apache.camel.quarkus%3Acamel-quarkus-csimple&e=org.apache.camel.quarkus%3Acamel-quarkus-csv&e=org.apache.camel.quarkus%3Acamel-quarkus-dataformat&e=org.apache.camel.quarkus%3Acamel-quarkus-debezium-mongodb&e=org.apache.camel.quarkus%3Acamel-quarkus-debezium-mysql&e=org.apache.camel.quarkus%3Acamel-quarkus-debezium-postgres&e=org.apache.camel.quarkus%3Acamel-quarkus-debezium-sqlserver&e=org.apache.camel.quarkus%3Acamel-quarkus-digitalocean&e=org.apache.camel.quarkus%3Acamel-quarkus-direct&e=org.apache.camel.quarkus%3Acamel-quarkus-disruptor&e=org.apache.camel.quarkus%3Acamel-quarkus-dozer&e=org.apache.camel.quarkus%3Acamel-quarkus-dropbox&e=org.apache.camel.quarkus%3Acamel-quarkus-elasticsearch-rest&e=org.apache.camel.quarkus%3Acamel-quarkus-exec&e=org.apache.camel.quarkus%3Acamel-quarkus-fhir&e=org.apache.camel.quarkus%3Acamel-quarkus-file&e=org.apache.camel.quarkus%3Acamel-quarkus-file-watch&e=org.apache.camel.quarkus%3Acamel-quarkus-flatpack&e=org.apache.camel.quarkus%3Acamel-quarkus-fop&e=org.apache.camel.quarkus%3Acamel-quarkus-freemarker&e=org.apache.camel.quarkus%3Acamel-quarkus-ftp&e=org.apache.camel.quarkus%3Acamel-quarkus-geocoder&e=org.apache.camel.quarkus%3Acamel-quarkus-git&e=org.apache.camel.quarkus%3Acamel-quarkus-github&e=org.apache.camel.quarkus%3Acamel-quarkus-google-bigquery&e=org.apache.camel.quarkus%3Acamel-quarkus-google-calendar&e=org.apache.camel.quarkus%3Acamel-quarkus-google-drive&e=org.apache.camel.quarkus%3Acamel-quarkus-google-mail&e=org.apache.camel.quarkus%3Acamel-quarkus-google-pubsub&e=org.apache.camel.quarkus%3Acamel-quarkus-google-sheets&e=org.apache.camel.quarkus%3Acamel-quarkus-google-storage&e=org.apache.camel.quarkus%3Acamel-quarkus-graphql&e=org.apache.camel.quarkus%3Acamel-quarkus-grok&e=org.apache.camel.quarkus%3Acamel-quarkus-grpc&e=org.apache.camel.quarkus%3Acamel-quarkus-gson&e=org.apache.camel.quarkus%3Acamel-quarkus-hazelcast&e=org.apache.camel.quarkus%3Acamel-quarkus-headersmap&e=org.apache.camel.quarkus%3Acamel-quarkus-hl7&e=org.apache.camel.quarkus%3Acamel-quarkus-http&e=org.apache.camel.quarkus%3Acamel-quarkus-hystrix&e=org.apache.camel.quarkus%3Acamel-quarkus-ical&e=org.apache.camel.quarkus%3Acamel-quarkus-infinispan&e=org.apache.camel.quarkus%3Acamel-quarkus-influxdb&e=org.apache.camel.quarkus%3Acamel-quarkus-ipfs&e=org.apache.camel.quarkus%3Acamel-quarkus-jackson&e=org.apache.camel.quarkus%3Acamel-quarkus-jacksonxml&e=org.apache.camel.quarkus%3Acamel-quarkus-jaxb&e=org.apache.camel.quarkus%3Acamel-quarkus-jdbc&e=org.apache.camel.quarkus%3Acamel-quarkus-jing&e=org.apache.camel.quarkus%3Acamel-quarkus-jira&e=org.apache.camel.quarkus%3Acamel-quarkus-jms&e=org.apache.camel.quarkus%3Acamel-quarkus-johnzon&e=org.apache.camel.quarkus%3Acamel-quarkus-jolt&e=org.apache.camel.quarkus%3Acamel-quarkus-jpa&e=org.apache.camel.quarkus%3Acamel-quarkus-jslt&e=org.apache.camel.quarkus%3Acamel-quarkus-jsonpath&e=org.apache.camel.quarkus%3Acamel-quarkus-json-validator&e=org.apache.camel.quarkus%3Acamel-quarkus-jsonb&e=org.apache.camel.quarkus%3Acamel-quarkus-jsonata&e=org.apache.camel.quarkus%3Acamel-quarkus-jta&e=org.apache.camel.quarkus%3Acamel-quarkus-kafka&e=org.apache.camel.quarkus%3Acamel-quarkus-kamelet&e=org.apache.camel.quarkus%3Acamel-quarkus-kotlin&e=org.apache.camel.quarkus%3Acamel-quarkus-kubernetes&e=org.apache.camel.quarkus%3Acamel-quarkus-kudu&e=org.apache.camel.quarkus%3Acamel-quarkus-leveldb&e=org.apache.camel.quarkus%3Acamel-quarkus-log&e=org.apache.camel.quarkus%3Acamel-quarkus-lra&e=org.apache.camel.quarkus%3Acamel-quarkus-lumberjack&e=org.apache.camel.quarkus%3Acamel-quarkus-lzf&e=org.apache.camel.quarkus%3Acamel-quarkus-mail&e=org.apache.camel.quarkus%3Acamel-quarkus-master&e=org.apache.camel.quarkus%3Acamel-quarkus-micrometer&e=org.apache.camel.quarkus%3Acamel-quarkus-microprofile-fault-tolerance&e=org.apache.camel.quarkus%3Acamel-quarkus-microprofile-health&e=org.apache.camel.quarkus%3Acamel-quarkus-microprofile-metrics&e=org.apache.camel.quarkus%3Acamel-quarkus-minio&e=org.apache.camel.quarkus%3Acamel-quarkus-mllp&e=org.apache.camel.quarkus%3Acamel-quarkus-mock&e=org.apache.camel.quarkus%3Acamel-quarkus-mongodb&e=org.apache.camel.quarkus%3Acamel-quarkus-mongodb-gridfs&e=org.apache.camel.quarkus%3Acamel-quarkus-msv&e=org.apache.camel.quarkus%3Acamel-quarkus-mustache&e=org.apache.camel.quarkus%3Acamel-quarkus-nagios&e=org.apache.camel.quarkus%3Acamel-quarkus-nats&e=org.apache.camel.quarkus%3Acamel-quarkus-netty&e=org.apache.camel.quarkus%3Acamel-quarkus-netty-http&e=org.apache.camel.quarkus%3Acamel-quarkus-nitrite&e=org.apache.camel.quarkus%3Acamel-quarkus-nsq&e=org.apache.camel.quarkus%3Acamel-quarkus-oaipmh&e=org.apache.camel.quarkus%3Acamel-quarkus-olingo4&e=org.apache.camel.quarkus%3Acamel-quarkus-openapi-java&e=org.apache.camel.quarkus%3Acamel-quarkus-openstack&e=org.apache.camel.quarkus%3Acamel-quarkus-opentelemetry&e=org.apache.camel.quarkus%3Acamel-quarkus-opentracing&e=org.apache.camel.quarkus%3Acamel-quarkus-optaplanner&e=org.apache.camel.quarkus%3Acamel-quarkus-paho&e=org.apache.camel.quarkus%3Acamel-quarkus-paho-mqtt5&e=org.apache.camel.quarkus%3Acamel-quarkus-pdf&e=org.apache.camel.quarkus%3Acamel-quarkus-platform-http&e=org.apache.camel.quarkus%3Acamel-quarkus-pgevent&e=org.apache.camel.quarkus%3Acamel-quarkus-pg-replication-slot&e=org.apache.camel.quarkus%3Acamel-quarkus-protobuf&e=org.apache.camel.quarkus%3Acamel-quarkus-jackson-protobuf&e=org.apache.camel.quarkus%3Acamel-quarkus-pubnub&e=org.apache.camel.quarkus%3Acamel-quarkus-quartz&e=org.apache.camel.quarkus%3Acamel-quarkus-qute&e=org.apache.camel.quarkus%3Acamel-quarkus-rabbitmq&e=org.apache.camel.quarkus%3Acamel-quarkus-reactive-executor&e=org.apache.camel.quarkus%3Acamel-quarkus-reactive-streams&e=org.apache.camel.quarkus%3Acamel-quarkus-ref&e=org.apache.camel.quarkus%3Acamel-quarkus-rest&e=org.apache.camel.quarkus%3Acamel-quarkus-rest-openapi&e=org.apache.camel.quarkus%3Acamel-quarkus-rss&e=org.apache.camel.quarkus%3Acamel-quarkus-saga&e=org.apache.camel.quarkus%3Acamel-quarkus-salesforce&e=org.apache.camel.quarkus%3Acamel-quarkus-sap-netweaver&e=org.apache.camel.quarkus%3Acamel-quarkus-scheduler&e=org.apache.camel.quarkus%3Acamel-quarkus-jsch&e=org.apache.camel.quarkus%3Acamel-quarkus-seda&e=org.apache.camel.quarkus%3Acamel-quarkus-servicenow&e=org.apache.camel.quarkus%3Acamel-quarkus-servlet&e=org.apache.camel.quarkus%3Acamel-quarkus-shiro&e=org.apache.camel.quarkus%3Acamel-quarkus-sjms&e=org.apache.camel.quarkus%3Acamel-quarkus-sjms2&e=org.apache.camel.quarkus%3Acamel-quarkus-slack&e=org.apache.camel.quarkus%3Acamel-quarkus-smallrye-reactive-messaging&e=org.apache.camel.quarkus%3Acamel-quarkus-snakeyaml&e=org.apache.camel.quarkus%3Acamel-quarkus-soap&e=org.apache.camel.quarkus%3Acamel-quarkus-solr&e=org.apache.camel.quarkus%3Acamel-quarkus-splunk&e=org.apache.camel.quarkus%3Acamel-quarkus-spring-rabbitmq&e=org.apache.camel.quarkus%3Acamel-quarkus-sql&e=org.apache.camel.quarkus%3Acamel-quarkus-ssh&e=org.apache.camel.quarkus%3Acamel-quarkus-stax&e=org.apache.camel.quarkus%3Acamel-quarkus-stream&e=org.apache.camel.quarkus%3Acamel-quarkus-stringtemplate&e=org.apache.camel.quarkus%3Acamel-quarkus-syslog&e=org.apache.camel.quarkus%3Acamel-quarkus-tagsoup&e=org.apache.camel.quarkus%3Acamel-quarkus-tarfile&e=org.apache.camel.quarkus%3Acamel-quarkus-telegram&e=org.apache.camel.quarkus%3Acamel-quarkus-threadpoolfactory-vertx&e=org.apache.camel.quarkus%3Acamel-quarkus-tika&e=org.apache.camel.quarkus%3Acamel-quarkus-timer&e=org.apache.camel.quarkus%3Acamel-quarkus-twilio&e=org.apache.camel.quarkus%3Acamel-quarkus-twitter&e=org.apache.camel.quarkus%3Acamel-quarkus-univocity-parsers&e=org.apache.camel.quarkus%3Acamel-quarkus-validator&e=org.apache.camel.quarkus%3Acamel-quarkus-velocity&e=org.apache.camel.quarkus%3Acamel-quarkus-vertx&e=org.apache.camel.quarkus%3Acamel-quarkus-vertx-http&e=org.apache.camel.quarkus%3Acamel-quarkus-vertx-kafka&e=org.apache.camel.quarkus%3Acamel-quarkus-vertx-websocket&e=org.apache.camel.quarkus%3Acamel-quarkus-vm&e=org.apache.camel.quarkus%3Acamel-quarkus-weather&e=org.apache.camel.quarkus%3Acamel-quarkus-xchange&e=org.apache.camel.quarkus%3Acamel-quarkus-xml-io-dsl&e=org.apache.camel.quarkus%3Acamel-quarkus-xml-jaxb&e=org.apache.camel.quarkus%3Acamel-quarkus-xml-jaxp&e=org.apache.camel.quarkus%3Acamel-quarkus-xmlsecurity&e=org.apache.camel.quarkus%3Acamel-quarkus-xpath&e=org.apache.camel.quarkus%3Acamel-quarkus-saxon&e=org.apache.camel.quarkus%3Acamel-quarkus-xslt&e=org.apache.camel.quarkus%3Acamel-quarkus-xstream&e=org.apache.camel.quarkus%3Acamel-quarkus-yaml-dsl&e=org.apache.camel.quarkus%3Acamel-quarkus-zendesk&e=org.apache.camel.quarkus%3Acamel-quarkus-zip-deflater&e=org.apache.camel.quarkus%3Acamel-quarkus-zipfile&e=io.debezium%3Adebezium-quarkus-outbox&e=org.kie.kogito%3Akogito-quarkus&e=org.kie.kogito%3Akogito-quarkus-decisions&e=org.kie.kogito%3Akogito-quarkus-predictions&e=org.kie.kogito%3Akogito-quarkus-rules&e=org.kie.kogito%3Akogito-quarkus-serverless-workflow&e=org.optaplanner%3Aoptaplanner-quarkus&e=org.optaplanner%3Aoptaplanner-quarkus-benchmark&cn=localhost

**Comment by phillip-kruger** [comment]
@ia3andy I could not recreate this locally. Above URL does the download all (I think). Maybe you can have a look at the log file on the staging server ?

**Comment by jeffmaury** [comment]
We're using post as get does not allow all extensions

**Comment by ia3andy** [comment]
here is the error in the log:
```
[ERROR] :exclamation: Failed to determine a compatible Quarkus version for the requested extensions: io.quarkus:quarkus-oidc-client-reactive-filter, org.apache.camel.quarkus:camel-quarkus-jpa, io.quarkus:quarkus-smallrye-jwt, io.quarkus:quarkus-spring-data-jpa, org.apache.camel.quarkus:camel-quarkus-github, io.quarkus:quarkus-narayana-jta, org.apache.camel.quarkus:camel-quarkus-hazelcast, org.apache.camel.quarkus:camel-quarkus-pg-replication-slot, org.apache.camel.quarkus:camel-quarkus-servicenow, io.quarkus:quarkus-smallrye-graphql-client, org.apache.camel.quarkus:camel-quarkus-sjms2, io.quarkus:quarkus-funqy-http, org.apache.camel.quarkus:camel-quarkus-jdbc, io.quarkus:quarkus-reactive-db2-client, org.apache.camel.quarkus:camel-quarkus-git, org.apache.camel.quarkus:camel-quarkus-syslog, io.quarkus:quarkus-rest-client-jsonb, io.quarkus:quarkus-hibernate-orm-panache-kotlin, org.apache.camel.quarkus:camel-quarkus-splunk, org.apache.camel.quarkus:camel-quarkus-tarfile, io.quarkus:quarkus-avro, org.apache.camel.quarkus:...
2021-08-20 14:35:15,206 ERROR [io.und.req.io] (executor-thread-1) Exception handling request 9a2e5680-f645-4ab7-a286-a84d1607c3fd-10 to /api/download: org.jboss.resteasy.spi.UnhandledException: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
```

I guess we now have a feature detecting incompatibilities, @aloubyansky will give more info

**Comment by aloubyansky** [comment]
That's a consequence of supporting more than one Quarkus version in the dev tools.
Depending on how the extensions are obtained, this kind of test might not make sense any more. Unless a Quarkus version is specified, the returned catalog will include extensions for all the Quarkus versions currently supported (for today the registry supports 2.0.3.Final, 2.1.3.Final and 2.2.0.CR1) . Some of those extensions may be compatible with one Quarkus version but not another. Trying to create a project containing all of those extension is expected to fail with an error similar to what is reported.

So the question is how is the list of extensions obtained in the test.

**Comment by jeffmaury** [comment]
Quarkus tools uses the same endpoint when retrieving extensions so no version is specified
Why the latest is not the default?

**Comment by aloubyansky** [comment]
Because in some cases we want to have a complete catalog and perform a smart target platform and version recommendation.

**Comment by aloubyansky** [comment]
You can obtain the latest recommended platform version and fetch an extension catalog based on its Quarkus core version.

**Comment by aloubyansky** [comment]
We could probably introduce such a method/endpoint to make it easier.

**Comment by aloubyansky** [comment]
The thing is that, other dev tools, such as the command line tools, do it differently. They obtain the complete catalog and recommend the Quarkus version based on the selected extensions.

**Comment by aloubyansky** [comment]
code.quarkus is going to be narrowing the catalogs to a specific stream (e.g. 2.0, 2.1, 2.2) a user could select (with the latest stream being the default). But even in the same stream **theoretically** (but practically unlikely) you may have incompatible extensions.

**Comment by aloubyansky** [comment]
All the project creation logic with the platform/version selection is in the devtools-common module. Which is used by the command line tools and code.quarkus. It's unfortunate the IDEs are not benefiting from it.

**Comment by aloubyansky** [comment]
So, I guess we could turn this issue into a feature request to provide a catalog limited to the latest recommended platform and Quarkus versions just to make it easier for the IDEs. But this means IDEs will work differently than the rest of the dev tools. Do you plan to support multiple streams like code.quarkus?

**Comment by jeffmaury** [comment]
Yes I will add version selection but existing installations may break from now if we keep as is

**Comment by aloubyansky** [comment]
Right. That's not good. Which endpoint is it?

**Comment by jeffmaury** [comment]
We're using /api/extensions and /api/download

**Comment by aloubyansky** [comment]
Actually, it might not be that bad. It's consistent with the command line tools where a user can select extensions and the tools will recommend the latest Quarkus version that works for the selection, assuming there is one. A user can also narrow the original catalog to a specific Quarkus platform stream or version. So, perhaps, the IDEs should add a feature to narrow the original catalog.

**Comment by maxandersen** [comment]
It is imo a *good* thing if we can keep the ides as "dumb" as possible. 

We should not expect clients being fine having to have a jar with client side logic. Our rest api should be sufficient and as little processing needed client side.

**Comment by aloubyansky** [comment]
AFAIU, correct me if I'm wrong @jeffmaury, the IDEs obtain the catalog of extensions from code.quarkus, let users pick the extensions and then call code.quarkus again to create the project. If that's the case, the common project gen code is still serving the IDEs in this case.

**Comment by jeffmaury** [comment]
Yes that the flow followed by Quarkus Tools with no version/stream selection yet. Should I had it ?

**Comment by aloubyansky** [comment]
It is consistent with the command line tools at least. So, imo, it's a valid option. Alternatively, you may choose the approach used by code.quarkus, which pre-selects the recommended stream (reflecting it in the UI) allowing the user to change it.

**Comment by ia3andy** [comment]
> Quarkus tools uses the same endpoint when retrieving extensions so no version is specified
> Why the latest is not the default?

@jeffmaury  I am currently discussing with @aloubyansky, as you said, it is supposed to use the recommended one by default (and not all the extensions). We will come back to you with further info..

**Comment by ia3andy** [comment]
ok @jeffmaury thanks to your test we found a bug introduced in 2.1.3.Final.

As @aloubyansky said, while working for now (without the bug), I don't think such a test is really relevant as compatibility is not guaranteed between extensions (even with the same Quarkus version). @aloubyansky will give you a better scenario to make sure everything's working fine..

Also, we in our side, should add testing for those kind of scenario with large set of extensions because we have more info to have similar tests..
