### ISSUE TITLE
Update code quarkus background images and modify color css

### ISSUE THREAD

**Issue by insectengine** [quarkusio/code.quarkus.io#557]
Images to update the header and form backgrounds:
**1920 pixel wide Images**
https://design.jboss.org/quarkus/website/website_2021redesign/images/1920wide/codebk_gradient_headerimage_violet_1920.jpg
https://design.jboss.org/quarkus/website/website_2021redesign/images/1920wide/codebk_gradient_formimage_violet_1920.jpg

**3000 pixel wide Images**
https://design.jboss.org/quarkus/website/website_2021redesign/images/3000wide/codebk_gradient_formimage_violet_3000.jpg
https://design.jboss.org/quarkus/website/website_2021redesign/images/3000wide/codebk_gradient_headerimage_violet_3000.jpg

(I'll also attach them to this issue)

Additional CSS changes needed:

1) In ".header" - Remove: "background-size: 100% 70px;" since it squishes the image.

2) In ".info-picker .form .form-group .form-group-label" - Change the label elements white instead of light blue.
![codebk_gradient_formimage_violet_1920](https://user-images.githubusercontent.com/928656/135929180-aa30b0f3-0358-48ff-b055-c6550c175268.jpg)
![codebk_gradient_headerimage_violet_1920](https://user-images.githubusercontent.com/928656/135929182-7cc61fbd-2e15-4cd9-8d4a-7cc57b5f22b5.jpg)
![codebk_gradient_formimage_violet_3000](https://user-images.githubusercontent.com/928656/135929183-878e6604-ea88-42b8-8d52-5e7b16c3b3a0.jpg)
![codebk_gradient_headerimage_violet_3000](https://user-images.githubusercontent.com/928656/135929184-0e9580f2-f762-40fd-8fb2-31fb34e1366a.jpg)

**Comment by ia3andy** [comment]
Awesome @insectengine :) thanks for this!!
