### ISSUE TITLE
Make it possible to see "non platform extensions"

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#584]
**Description**

The api already supports it, we now need to make it possible to see them in the UI. 

Such extensions should have a new tag that explains that they are non platform and what it implies (bom, trust, ...)

**Comment by ia3andy** [comment]
I would add it as a checkbox (unselected by default) under the list of streams:
![image](https://user-images.githubusercontent.com/2223984/136046162-49f81602-ce05-41de-ad1d-309ffc7fc5b0.png)

**Comment by ia3andy** [comment]
@maxandersen nothing is holding, we have the choice.. This is just closer to where the data is loaded, while the search is happening in the UI, so the other option would be to load it anyway but hide it if not checked (in the search)

**Comment by maxandersen** [comment]
I think that makes more sense assuming the extra data is not going to slow down the load of the page. 

Otherwise don't we have api to load this as needed async in the search ?

**Comment by ia3andy** [comment]
> I think that makes more sense assuming the extra data is not going to slow down the load of the page.
> 
> Otherwise don't we have api to load this as needed async in the search ?

We could, it just involves a bit more logic..

**Comment by maxandersen** [comment]
summary from chat/discussion 2021-11-05:
Participants: @aloubyansky @ia3andy @maxandersen 

whether an extension is in or outside a platform matters. The tooling can handle the mechanics but adding from outsid platform means version is non-managed and updates and expecatiosns on what will work is different.
i.e. having "cxf" being added to a project should not be as "easy" as as adding "reactive messaging" - users should be aware they are stepping "outside"

At same time we do want to make external extensions discoverable even without user having to know to search for them.

Idea is for cli/IDE/code.quarkus to default to showing origin=platform results if a unique platform is chosen, but do inform results are found outside too. 

For cli that could look something like:

in cli:
```
quarkus ext list -s github
Current Quarkus extensions available:
* Camel GitHub                                       2.4.0                                                        io.quarkus.platform:quarkus-camel-bom::pom:2.4.1.Final
                                                                                                                io.quarkus.platform:quarkus-camel-bom::pom:2.3.1.Final

1 extension in platform, 2 extension(s) found with other origin. Run with --origin=any to see.

To get more information, append `--full` to your command line.

To list only extensions from specific category, append `--category "categoryId"` to your command line.
```

```
quarkus ext list --orgin=any -s github
Current Quarkus extensions available:
* Camel GitHub                                       2.4.0                                                        io.quarkus.platform:quarkus-camel-bom::pom:2.4.1.Final
                                                                                                                io.quarkus.platform:quarkus-camel-bom::pom:2.3.1.Final
  Quarkus GitHub API                                 1.131.1
  Quarkus GitHub App                                 1.2.1
3 extensions found.
```
 
And on code.quarkus it would be something like:

<img width="1239" alt="2021-11-05_16-23-00" src="https://user-images.githubusercontent.com/54129/140535670-7fecd56f-c843-4b50-85f2-2271bb3cb184.png">

And then if clicking on "2 found" it will show with orgin=any:


<img width="1239" alt="2021-11-05_16-23-00 copy" src="https://user-images.githubusercontent.com/54129/140535875-86781be1-ef69-4d49-af7f-54df073e3eb0.png">

Also discussed adding a "blue dot" on any extension inside a platform to make it visually distinct from non-platform without putting a "negative" term or icon on those from origin outside platform.

@ia3andy will make a first cut of this available next week so we can try it for real.

**Comment by ia3andy** [comment]
It's done :)
