### ISSUE TITLE
Code Quarkus Publish NPM Library CI is failing when triggered by dependabot

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#585]
**Describe the bug**
Code Quarkus Publish NPM Library CI is failing when triggered by dependabot:
https://github.com/quarkusio/code.quarkus.io/actions/workflows/code-quarkus-library-publish-actions.yml

We need to change the workflow not run if it's trigger by the bot (another option would be to look if the message contains "Bump", but it's not as clean):
https://github.community/t/how-to-stop-github-actions-workflow-to-trigger-when-the-pull-request-is-from-dependabot-preview/116486

**Comment by maxandersen** [comment]
What's unique about dependabot? Is it not any PR that will have such issue ?

**Comment by ia3andy** [comment]
No, everything works fine if I merge the PR.

I assume it's because the owner is the bot when triggered by dependabot, and some kind of bug (or security) prevent from using the Git PAT token in that case:
https://github.com/quarkusio/code.quarkus.io/blob/main/.github/workflows/code-quarkus-library-publish-actions.yml#L22
