### ISSUE TITLE
Button to store current app as default (in local storage) 

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#591]
**Description**
I would be nice to have a button to store the current app as default (in local storage).

We could put it in the Generate Menu "Store current app as default":
![image](https://user-images.githubusercontent.com/2223984/136328886-35ca8952-dfed-4f07-ac2a-8d8710f24edd.png)

**Comment by ia3andy** [comment]
Implementation Idea:

1- Get the project from the local storage in `resolveInitialProject()`:
https://github.com/quarkusio/code.quarkus.io/blob/ea6df92c5d0fd3a21fe986b7dd424c63a45b2b41/library/components/api/quarkus-project-utils.ts#L226

2- Set the project in local storage when clicking on the new button


Override order: Query params > localstorage > default

**Comment by tacsio** [comment]
@ia3andy, I have some questions about this issue. Could you help me?

* When clicking the new button, the new project should be downloaded after the configuration is saved to storage?

* Bookmark icon is a good choice for this button?
![Screenshot from 2022-06-21 13-10-29](https://user-images.githubusercontent.com/353197/174856619-55cc7f13-3a8b-4012-ac3f-6e98140b7cea.png)

* When github button is used, analytics event is fired, is necessary to send some event when clicking to store default app?

https://github.com/quarkusio/code.quarkus.io/blob/36cfa47f509a7474993aaa4ef56f08f8a42ff03e/library/components/generate-project/generate-button.tsx#L46-L49

**Comment by ia3andy** [comment]
> @ia3andy, I have some questions about this issue. Could you help me?
> 
> * When clicking the new button, the new project should be downloaded after the configuration is saved to storage?

No but it would be nice to have something showing the action worked, maybe a tooltip or something.

> * Bookmark icon is a good choice for this button?
>   ![Screenshot from 2022-06-21 13-10-29](https://github.com/assets/353197/55cc7f13-3a8b-4012-ac3f-6e98140b7cea)
> * When github button is used, analytics event is fired. Is necessary to send some event when clicking to store default app?
> 
> https://github.com/quarkusio/code.quarkus.io/blob/36cfa47f509a7474993aaa4ef56f08f8a42ff03e/library/components/generate-project/generate-button.tsx#L46-L49

Nop it's not needed

**Comment by tacsio** [comment]
Hey @ia3andy, I've almost finished this issue. 

Do you think any improvement is needed? 
![quarkus-save-button](https://user-images.githubusercontent.com/353197/176939903-1dff2289-faa8-4e6e-a006-42ec5448450c.gif)

**There is one more thing that I need some help before submitting the PR.**

I've tried some exceptional cases in my manual tests and find out this.

The app crashes if the project JSON is missing 'metadata' or 'extensions' entries.

```ts
export interface QuarkusProject {
  metadata: {
    groupId: string;
    artifactId: string;
    version: string;
    name?: string;
    noCode?: boolean;
    buildTool: string;
    javaVersion: string;
  };
  extensions: string[];
  streamKey?: string;
  platformOnly?: boolean;
  github?: {
    code: string;
    state: string;
  };
}
```

When I parse JSON as QuarkusProject interface, everything works fine, even if we don't have metadata or extensions defined.
 
```ts
JSON.parse(jsonProject!) as QuarkusProject;
```

Do you think a validation step of the JSON (looking for metadata and extensions) is needed? 
The only possible way to break the frontend like this is manually changing the value of the JSON after storing it in localstorage.


https://github.com/tacsio/code.quarkus.io/blob/71bd3194dfc4cb3f04d278dfcfc5f62eea6b1733/library/components/api/quarkus-project-utils.ts#L291-L303

**Comment by ia3andy** [comment]
@tacsio do you still have this code, really sorry I missed your message...

**Comment by tacsio** [comment]
Hey @ia3andy , I do... 
Sorry, I forgot to create a pull request.
I've created a simple validation to prevent errors if someone "hard edits" the project JSON representation in local storage.

```ts
function isValidQuarkusProject(project : QuarkusProject): Boolean {
  const valid = project.metadata !== undefined && 
                project.metadata.groupId !== undefined &&
                project.metadata.artifactId !== undefined &&
                project.metadata.version !== undefined &&
                project.metadata.buildTool !== undefined &&
                project.metadata.javaVersion !== undefined &&
                project.extensions !== undefined;
  return valid;
```
