### ISSUE TITLE
Generate required datasource properties automatically

### ISSUE THREAD

**Issue by jclingan** [quarkusio/code.quarkus.io#61]
Some extensions require properties be set in order to operate properly. This is true for JPA/JDBC. 

For H2, identified by the inclusion of the quarkus-jdbc-h2 extension, the following properties should be automatically generated in the application.properties file. These can be hard-coded or even as a pre-filled-in property list on the UI that a user can override (much like the GAVs are already):

%dev.quarkus.datasource.url=jdbc:h2:mem:test
%dev.quarkus.datasource.driver=org.h2.Driver
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.log-sql=true

For PostgreSQL, identified by the inclusion of the quarkus-jdbc-postgres extension, the following properties should be automatically generated in the application.properties file:

\# Please provide hostname, port, database name, username, and password
%dev.quarkus.datasource.driver: org.postgresql.Driver
%dev.quarkus.datasource.url: jdbc:postgresql://\<hostname\>:\<port\>/\<database\>
%dev.quarkus.datasource.username: \<username\>
%dev.quarkus.datasource.password: \<password\>
\# Uncomment the following line to generate the database schema
\#%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.log-sql=true

Note, this feature could potentially be added to the quarkus:add-extension goal as this property-generation feature could be cross-cutting feature across extensions. Where/how this is implemented is a discussion left for engineering.

**Comment by jclingan** [comment]
I should note that additional database support can be added (mongo, neo4j, MariaDB, etc).

**Comment by jclingan** [comment]
In hindsight, prepending generated properties with a %dev is a bad idea. Developers will want to generate native images when getting started/learning, as will those doing demos and conference/JUG talks. %dev will break the native image build or even running via java -jar, so let's not generate %dev profile string by default or we can discuss making it a checkbox UI option.

**Comment by ia3andy** [comment]
@jclingan the project creation is done by the quarkus library. Could you create an issue there?
