### ISSUE TITLE
When selecting Quarkiverse extensions I receive incorrect BOM snippet details

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/code.quarkus.io#690]
When selecting Quarkiverse extensions I receive incorrect BOM snippet details.

For example https://code.quarkus.io/?extension-search=origin:other%20jgraph gives 

![Screenshot 2021-12-06 at 10 44 55](https://user-images.githubusercontent.com/925259/144824035-f797c9c2-35f2-44fe-90f5-2355d6989e27.png)

I think there is no BOM attached to Quarkiverse extensions so BOM snippet details do not make sense

IMHO Dependency snippet should be extended to cover concrete version (for Quarkiverse extensions), now it covers groupId and artifactId:
```xml     
        <dependency>
            <groupId>io.quarkiverse.jgrapht</groupId>
            <artifactId>quarkus-jgrapht</artifactId>
        </dependency>
```

**Comment by rsvoboda** [comment]
@ia3andy / @maxandersen fyi

**Comment by ia3andy** [comment]
Duplicate https://github.com/quarkusio/code.quarkus.io/issues/689

**Comment by rsvoboda** [comment]
ah, thanks

**Comment by ia3andy** [comment]
I close the other one this one is better, I created mine really quickly to not forget :)
