### ISSUE TITLE
Dropdown arrow for Build Tool doesn't do anything

### ISSUE THREAD

**Issue by gsmet** [quarkusio/code.quarkus.io#727]
When going to https://code.quarkus.io/, clicking on the arrow at the end of the Build Tool dropdown doesn't do anything.

Clicking on `Maven` works and the dropdown appears but it's pretty counter intuitive.

Tested with Firefox 95.0.2.

**Comment by gsmet** [comment]
BTW, is the Gradle support still in preview?

**Comment by tacsio** [comment]
@gsmet, Can I work in that Issue?

**Comment by gsmet** [comment]
@tacsio sure, that would be awesome!

**Comment by tacsio** [comment]
@gsmet, just a question.
I've noticed that after run make tag-lib the library/.bitmap file shows that exists changes to quarkusio.code-quarkus/core/components@0.0.7 (but I didn't change anything in core components).
