### ISSUE TITLE
code.quarkus is reporting Quarkus Core version and not Quarkus platform version

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/code.quarkus.io#754]
code.quarkus is reporting Quarkus Core version and not Quarkus platform version

 - go to https://code.quarkus.io/
 - Hover mouse above stream selection

![Screenshot 2022-01-31 at 15 21 22](https://user-images.githubusercontent.com/925259/151810492-6f0df991-7fbb-4b8a-8f3d-f8c6dd970afb.png)

`<div class="quarkus-stream final" title="Quarkus core version: 2.6.3.Final"><span class="unselected"></span><span class="platform-key">io.quarkus.platform</span><span class="stream-id">2.6</span></div>`

I believe Quarkus Platform version should be reported there, not Quarkus Core one.

**Comment by maxandersen** [comment]
> I believe Quarkus Platform version should be reported there, not Quarkus Core one.

what if/when the platform stream starts having a version that is different than core, i.e. org.acme:1.2 ? wouldn't you find it relevant to know what Quarkus core that platform is targeting?

**Comment by rsvoboda** [comment]
Ideally both should be reported, but in case one is reported, I'm in favor of Quarkus platform version

**Comment by ia3andy** [comment]
I need to check if I have access to the platform version you are referring to in the registry client data (https://github.com/quarkusio/code.quarkus.io/blob/main/api/src/main/kotlin/io/quarkus/code/service/PlatformService.kt#L139). @aloubyansky any pointer?

**Comment by aloubyansky** [comment]
If you are using `io.quarkus.registry.client.Platform*` API then `PlatformRelease` has a version.

**Comment by rsvoboda** [comment]
@ia3andy any plans with this?

**Comment by ia3andy** [comment]
Yes I'll do it when I get the time

**Comment by ia3andy** [comment]
It's fixed an in production both community and RH product
