### ISSUE TITLE
Clicking multiple times on filters add them indefinitely

### ISSUE THREAD

**Issue by mmuzikar** [quarkusio/code.quarkus.io#772]
**Description**
Imagine someone is clicking through the filters in code.quarkus there's no way to switch a filter off.
For example I with filter `cat:integration origin:platform` there are options `stable,deprecated,preview,experimental` If I miss-clicked on the deprecated tag there's no way to remove that tag except manually. When it's clicked on again it only adds the tag again. Which is inconvenient :/

It would be cool if there were a little *x* buttons to remove the filter. Either in the selection dropdown, the current filter expression, or in the best case both.

**Comment by ia3andy** [comment]
The idea is to only show the filters that are in the current list and drill down toward the result by adding more filters.

Then, if you want to start over on a new search, you need to hit "Clear" and start again.

BTW you can do OR this way: `cat:integration,web` or `tag:stable,preview`.

**Comment by ia3andy** [comment]
If we really want something like this (and keep the drilling down logic) we need 3 states for the button (active/inactive/disabled) which seems a bit complex.

**Comment by mmuzikar** [comment]
I should've probably split the issue in 2. The bigger issue IMO is when this is happening:
![Peek 2022-02-21 18-24](https://user-images.githubusercontent.com/46345469/155002393-93456512-b37c-423a-a5f2-f0c70bfb15d3.gif)
 
The option staying there evokes that it's a toggle, but clicking on it just keeps adding to the query and there's no other option than to erase the label "manually".
