### ISSUE TITLE
Clicking on tag links also adds the extension

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#839]
This is only affecting code.quarkus.redhat.com

**Comment by tqvarnst** [comment]
@ia3andy Do we plan to fix this or should we close it as wontfix?

**Comment by ia3andy** [comment]
> code.quarkus.redhat.com

Not sure, I think it's better to keep it as it's still a bug.

The fix needs a bit of investigation and tryouts, if you think it's important, I could manage to find some time (or anyone could also have a look)
