### ISSUE TITLE
Switch to Google Analytics 4

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#864]
**Describe the bug**
Support for Universal Analytics will be dropped on July 1st 2023.

**Comment by maxandersen** [comment]
https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4/

**Comment by insectengine** [comment]
@ia3andy - Axel Kandel created a new Quarkus GA4 analytics account. We've added this to Quarkus.io via Google Tag Manager. Do we want to use the same tracking number so we can better track traffic between the main site and the code app?

**Comment by ia3andy** [comment]
> @ia3andy - Axel Kandel created a new Quarkus GA4 analytics account. We've added this to Quarkus.io via Google Tag Manager. Do we want to use the same tracking number so we can better track traffic between the main site and the code app?

TBH I haven't looked at it yet, I will do soon!

**Comment by insectengine** [comment]
We need to sort out if we can stick with Google 4 or need to dump it for Adobe.

**Comment by ia3andy** [comment]
Yeah..

**Comment by maxandersen** [comment]
@insectengine is there a deadline to move to adobe ? is adobe cleared for use in community sites?

**Comment by maxandersen** [comment]
...and how do one get access to the adobe based stats?

**Comment by ia3andy** [comment]
Hey Max, I will keep you up to date on this matter when I get back (I was supposed to do it before but things become a bit out of hand on my side). 

Just to you know, we have it under control.

**Comment by insectengine** [comment]
No clear deadlines but we have adobe running on Quarkus.io but we're working out issues to get it running on Code (or an alternative).  

AdobeA also doesn't have a clear preset report like the old Google UA. but there are several reports created by Axel. One issue with AdobeA is you have to put in a service ticket to get access. 

https://source.redhat.com/departments/marketing/marketing_technology_and_operations/adobe_analytics


As a way around this, I've added a worksheet in the monthly Upstream projects report for Quarkus's AdobeA data. 
https://docs.google.com/spreadsheets/d/1IfZQKntmD4l7PP0_Gw7J5xTsp3e1IWT0RT6yjdBwGoo/edit#gid=1280501868
