### ISSUE TITLE
Add an explicite share button 

### ISSUE THREAD

**Issue by aoudiamoncef** [quarkusio/code.quarkus.io#891]
![image](https://user-images.githubusercontent.com/22281426/171409493-3df18779-a145-494b-8c1d-5d4e134eff15.png)

Hi @ia3andy,

I tried [code.quarkus.io](https://github.com/quarkusio/code.quarkus.io) and IMHO, it could interesting to add an explicite share button. 

I forked the projet and I saw the code, the function is already there.

I'm waiting for feedback.

Thanks

**Comment by ia3andy** [comment]
Hi @aoudiamoncef,

We had a share button in the past, but most people were copying the url:
- either in the browser to get the app pre-configured but not zipped yet
- either the zip (right click on "Generate" then copy link address)

**Comment by ia3andy** [comment]
Would you see a real value in integrating it in Quarkus, I mean you will most likely have your flutter app separated from the backend no?

**Comment by aoudiamoncef** [comment]
I understand, thanks for your reply. Feel free to close this issue. 
Regards
