### ISSUE TITLE
Crash in Chrome tab on code.quarkus.io

### ISSUE THREAD

**Issue by llowinge** [quarkusio/code.quarkus.io#912]
**Describe the bug**
Click on https://code.quarkus.io/?extension-search=camel-quarkus-azure-storage-queue
see there is not responsive box which cannot be clicked. After some time, chrome tab crashes.

**Expected behavior**
The page is responsible and doesn't crash.

**Environment (please complete the following information):**
 - Browser: Chrome Version 102.0.5005.115
 - OS: MacOS 10.15.7

**Comment by mmuzikar** [comment]
Addition: there hasn't been release of Camel Extensions for Quarkus for that version so it's probably the cause. 
And also this doesn't crash firefox but firefox is unresponsive for a few seconds when clicking on the link.
