### ISSUE TITLE
Support for older Quarkus versions

### ISSUE THREAD

**Issue by xorye** [quarkusio/code.quarkus.io#95]
Unless I am not mistaken, it seems like we can only create projects with the latest version of Quarkus. It would be nice if there was an option to decide which Quarkus version to make a project with. If a specific Quarkus version is selected, the extensions list would also show extensions that are available for that specific Quarkus version. 

It would be fantastic if a "version" query parameter could be added to the `quarkus/extensions` and `quarkus/download` endpoints to facilitate this feature. That would be extremely helpful in our particular use case.

**Comment by tqvarnst** [comment]
I just want to second this, it's also good to indicate which is the latest promoted release.

**Comment by ia3andy** [comment]
This feature needs to be implemented in Quarkus first. The Launcher is just delegating the generation to it.

@tqvarnst What do you think, as a temporary workaround, about showing a select box with only one choice beeing the last version?
