### ISSUE TITLE
Inform the user about managing extensions after bootstrap

### ISSUE THREAD

**Issue by jotak** [quarkusio/code.quarkus.io#99]
The project bootstrap allows to add any extension and shows the related maven command.

However, one may wonder how they can edit their choice later / remove extensions, especially when adding extensions goes through an opaque mvn command rather than simple pom edition (even if in the end it's just pom edition, it's still opaque).

So, is there an equivalent command such as `./mvnw quarkus:remove-extension -Dextensions="..."` ? ; if so, maybe it should be noted somewhere on the bootstrap page?

**Comment by ia3andy** [comment]
Thanks @jotak this is a good feedback, I'll try to find a solution to make it more obvious.. if you feel like contributing don't hesitate 😁
